scan_targets:
  - registry: dockerhub
    auth:
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
    images:
      - name: hasura/graphql-engine
        tags:
          - v2.36.0
#          - v2.36.3
##          - v2.11.13
        scan_policy:
          vulnerabilities:
            - CRITICAL
            - HIGH
          notify:
            - tool: Linear
              api_key: ${LINEAR_API_KEY}
              project_id: 24c2aac3-638a-4824-8371-26f250fbaed1
              team_id: e9f2cd02-7113-4ec3-bb08-ea7a151f542a
              issue_title: TEST2 Vulnerability Report
              issue_priority: 2
              issue_assignee_id: d74e16a8-b9e4-4fcf-a2d5-da01787f1678 # UUID of Assignee, here its ashwini@hasura.io
              issue_state_id: 822cf3fe-a0bd-4401-9423-310c4f27d71f # UUID of Backlog, Triage, In progres etc
              issue_due_date: 2024-12-01 #YYYY-MM-DD
      - name: hasura/graphql-engine # other repository
        tags:
          - v2.36.4
          - v2.11.8
        scan_policy:
          vulnerabilities:
            - CRITICAL
            - HIGH
          notify:
            - tool: Linear
              api_key: lin_api_Yhx5B3z6Tko6x0ZAJT0rtfvwMrspzposr1DwiK4y
              project_id: 24c2aac3-638a-4824-8371-26f250fbaed1
              team_id: e9f2cd02-7113-4ec3-bb08-ea7a151f542a
              issue_title: TEST2 Vulnerability Report
              issue_priority: 2
              issue_assignee_id: d74e16a8-b9e4-4fcf-a2d5-da01787f1678
              issue_state_id: 822cf3fe-a0bd-4401-9423-310c4f27d71f
              issue_due_date: 2024-12-01 #YYYY-MM-DD
    scanner:
      - tool: Trivy
website:
  hostname: localhost
  files_path: /Users/ashwinigaddagi/work/goKakashi/test_data # absolute
  public:
    port: 8080
  private:
    port: 9090
