// Code generated by ent, DO NOT EDIT.

package scanpolicy

import (
	"entgo.io/ent/dialect/sql"
	"github.com/shinobistack/gokakashi/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldEQ(FieldName, v))
}

// TriggerType applies equality check predicate on the "trigger_type" field. It's identical to TriggerTypeEQ.
func TriggerType(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldEQ(FieldTriggerType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldContainsFold(FieldName, v))
}

// TriggerTypeEQ applies the EQ predicate on the "trigger_type" field.
func TriggerTypeEQ(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldEQ(FieldTriggerType, v))
}

// TriggerTypeNEQ applies the NEQ predicate on the "trigger_type" field.
func TriggerTypeNEQ(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldNEQ(FieldTriggerType, v))
}

// TriggerTypeIn applies the In predicate on the "trigger_type" field.
func TriggerTypeIn(vs ...string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldIn(FieldTriggerType, vs...))
}

// TriggerTypeNotIn applies the NotIn predicate on the "trigger_type" field.
func TriggerTypeNotIn(vs ...string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldNotIn(FieldTriggerType, vs...))
}

// TriggerTypeGT applies the GT predicate on the "trigger_type" field.
func TriggerTypeGT(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldGT(FieldTriggerType, v))
}

// TriggerTypeGTE applies the GTE predicate on the "trigger_type" field.
func TriggerTypeGTE(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldGTE(FieldTriggerType, v))
}

// TriggerTypeLT applies the LT predicate on the "trigger_type" field.
func TriggerTypeLT(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldLT(FieldTriggerType, v))
}

// TriggerTypeLTE applies the LTE predicate on the "trigger_type" field.
func TriggerTypeLTE(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldLTE(FieldTriggerType, v))
}

// TriggerTypeContains applies the Contains predicate on the "trigger_type" field.
func TriggerTypeContains(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldContains(FieldTriggerType, v))
}

// TriggerTypeHasPrefix applies the HasPrefix predicate on the "trigger_type" field.
func TriggerTypeHasPrefix(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldHasPrefix(FieldTriggerType, v))
}

// TriggerTypeHasSuffix applies the HasSuffix predicate on the "trigger_type" field.
func TriggerTypeHasSuffix(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldHasSuffix(FieldTriggerType, v))
}

// TriggerTypeEqualFold applies the EqualFold predicate on the "trigger_type" field.
func TriggerTypeEqualFold(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldEqualFold(FieldTriggerType, v))
}

// TriggerTypeContainsFold applies the ContainsFold predicate on the "trigger_type" field.
func TriggerTypeContainsFold(v string) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.FieldContainsFold(FieldTriggerType, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScanPolicy) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScanPolicy) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScanPolicy) predicate.ScanPolicy {
	return predicate.ScanPolicy(sql.NotPredicates(p))
}
