services:
  gokakashi-server:
    extends:
      file: base.yaml
      service: gokakashi-server
    command: server --config=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml

networks:
  gokakashi-network:

volumes:
  pgdata:
  workspace:
