// Code generated by ent, DO NOT EDIT.

package v2agents

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/shinobistack/gokakashi/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldLTE(FieldID, id))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEQ(FieldStatus, v))
}

// LastHeartbeatAt applies equality check predicate on the "last_heartbeat_at" field. It's identical to LastHeartbeatAtEQ.
func LastHeartbeatAt(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEQ(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldContainsFold(FieldStatus, v))
}

// LastHeartbeatAtEQ applies the EQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtEQ(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtNEQ applies the NEQ predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNEQ(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNEQ(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIn applies the In predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIn(vs ...time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtNotIn applies the NotIn predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotIn(vs ...time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNotIn(FieldLastHeartbeatAt, vs...))
}

// LastHeartbeatAtGT applies the GT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGT(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldGT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtGTE applies the GTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtGTE(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldGTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLT applies the LT predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLT(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldLT(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtLTE applies the LTE predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtLTE(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldLTE(FieldLastHeartbeatAt, v))
}

// LastHeartbeatAtIsNil applies the IsNil predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtIsNil() predicate.V2Agents {
	return predicate.V2Agents(sql.FieldIsNull(FieldLastHeartbeatAt))
}

// LastHeartbeatAtNotNil applies the NotNil predicate on the "last_heartbeat_at" field.
func LastHeartbeatAtNotNil() predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNotNull(FieldLastHeartbeatAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.V2Agents {
	return predicate.V2Agents(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.V2Agents) predicate.V2Agents {
	return predicate.V2Agents(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.V2Agents) predicate.V2Agents {
	return predicate.V2Agents(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.V2Agents) predicate.V2Agents {
	return predicate.V2Agents(sql.NotPredicates(p))
}
