scan_targets:
  - registry: dockerhub
    auth:
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
    images:
      - name: xx/xx
        tags:
          - v2.36.0
          - v2.36.3
        scan_policy:
          vulnerabilities:
            - CRITICAL
            - HIGH
          notify:
            Linear:
              api_key: ${LINEAR_API_KEY}
              project_id: UUID
              team_id: UUID
              issue_title: TEST2 Vulnerability Report
              issue_priority: 2
              issue_assignee_id: UUID of Assignee
              issue_state_id: UUID of Backlog, Triage, In progres etc
              issue_due_date: 2024-12-01 #YYYY-MM-DD
      - name: xx/xx # other repository
        tags:
          - v2.36.4
          - v2.11.8
        scan_policy:
          vulnerabilities:
            - CRITICAL
            - HIGH
          notify:
            Jira:
              api_key: ${LINEAR_API_KEY}
              project_id: UUID
              team_id: UUID
              issue_title: TEST2 Vulnerability Report
              issue_priority: 2
              issue_assignee_id: UUID of Assignee
              issue_state_id: UUID of Backlog, Triage, In progres etc
              issue_due_date: 2024-12-01 #YYYY-MM-DD
    scanner:
      - tool: Trivy
website:
  hostname: localhost
  files_path: /app/website # absolute
  public:
    port: 8080
  private:
    port: 9090

