// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ScanPoliciesColumns holds the columns for the "scan_policies" table.
	ScanPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "trigger_type", Type: field.TypeString},
	}
	// ScanPoliciesTable holds the schema information for the "scan_policies" table.
	ScanPoliciesTable = &schema.Table{
		Name:       "scan_policies",
		Columns:    ScanPoliciesColumns,
		PrimaryKey: []*schema.Column{ScanPoliciesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ScanPoliciesTable,
	}
)

func init() {
}
