// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shinobistack/gokakashi/ent/agentsv2"
	"github.com/shinobistack/gokakashi/ent/predicate"
)

// AgentsV2Query is the builder for querying AgentsV2 entities.
type AgentsV2Query struct {
	config
	ctx        *QueryContext
	order      []agentsv2.OrderOption
	inters     []Interceptor
	predicates []predicate.AgentsV2
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AgentsV2Query builder.
func (av *AgentsV2Query) Where(ps ...predicate.AgentsV2) *AgentsV2Query {
	av.predicates = append(av.predicates, ps...)
	return av
}

// Limit the number of records to be returned by this query.
func (av *AgentsV2Query) Limit(limit int) *AgentsV2Query {
	av.ctx.Limit = &limit
	return av
}

// Offset to start from.
func (av *AgentsV2Query) Offset(offset int) *AgentsV2Query {
	av.ctx.Offset = &offset
	return av
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (av *AgentsV2Query) Unique(unique bool) *AgentsV2Query {
	av.ctx.Unique = &unique
	return av
}

// Order specifies how the records should be ordered.
func (av *AgentsV2Query) Order(o ...agentsv2.OrderOption) *AgentsV2Query {
	av.order = append(av.order, o...)
	return av
}

// First returns the first AgentsV2 entity from the query.
// Returns a *NotFoundError when no AgentsV2 was found.
func (av *AgentsV2Query) First(ctx context.Context) (*AgentsV2, error) {
	nodes, err := av.Limit(1).All(setContextOp(ctx, av.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{agentsv2.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (av *AgentsV2Query) FirstX(ctx context.Context) *AgentsV2 {
	node, err := av.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AgentsV2 ID from the query.
// Returns a *NotFoundError when no AgentsV2 ID was found.
func (av *AgentsV2Query) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = av.Limit(1).IDs(setContextOp(ctx, av.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{agentsv2.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (av *AgentsV2Query) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := av.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AgentsV2 entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AgentsV2 entity is found.
// Returns a *NotFoundError when no AgentsV2 entities are found.
func (av *AgentsV2Query) Only(ctx context.Context) (*AgentsV2, error) {
	nodes, err := av.Limit(2).All(setContextOp(ctx, av.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{agentsv2.Label}
	default:
		return nil, &NotSingularError{agentsv2.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (av *AgentsV2Query) OnlyX(ctx context.Context) *AgentsV2 {
	node, err := av.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AgentsV2 ID in the query.
// Returns a *NotSingularError when more than one AgentsV2 ID is found.
// Returns a *NotFoundError when no entities are found.
func (av *AgentsV2Query) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = av.Limit(2).IDs(setContextOp(ctx, av.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{agentsv2.Label}
	default:
		err = &NotSingularError{agentsv2.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (av *AgentsV2Query) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := av.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AgentsV2s.
func (av *AgentsV2Query) All(ctx context.Context) ([]*AgentsV2, error) {
	ctx = setContextOp(ctx, av.ctx, ent.OpQueryAll)
	if err := av.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AgentsV2, *AgentsV2Query]()
	return withInterceptors[[]*AgentsV2](ctx, av, qr, av.inters)
}

// AllX is like All, but panics if an error occurs.
func (av *AgentsV2Query) AllX(ctx context.Context) []*AgentsV2 {
	nodes, err := av.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AgentsV2 IDs.
func (av *AgentsV2Query) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if av.ctx.Unique == nil && av.path != nil {
		av.Unique(true)
	}
	ctx = setContextOp(ctx, av.ctx, ent.OpQueryIDs)
	if err = av.Select(agentsv2.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (av *AgentsV2Query) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := av.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (av *AgentsV2Query) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, av.ctx, ent.OpQueryCount)
	if err := av.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, av, querierCount[*AgentsV2Query](), av.inters)
}

// CountX is like Count, but panics if an error occurs.
func (av *AgentsV2Query) CountX(ctx context.Context) int {
	count, err := av.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (av *AgentsV2Query) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, av.ctx, ent.OpQueryExist)
	switch _, err := av.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (av *AgentsV2Query) ExistX(ctx context.Context) bool {
	exist, err := av.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AgentsV2Query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (av *AgentsV2Query) Clone() *AgentsV2Query {
	if av == nil {
		return nil
	}
	return &AgentsV2Query{
		config:     av.config,
		ctx:        av.ctx.Clone(),
		order:      append([]agentsv2.OrderOption{}, av.order...),
		inters:     append([]Interceptor{}, av.inters...),
		predicates: append([]predicate.AgentsV2{}, av.predicates...),
		// clone intermediate query.
		sql:  av.sql.Clone(),
		path: av.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AgentsV2.Query().
//		GroupBy(agentsv2.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (av *AgentsV2Query) GroupBy(field string, fields ...string) *AgentsV2GroupBy {
	av.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AgentsV2GroupBy{build: av}
	grbuild.flds = &av.ctx.Fields
	grbuild.label = agentsv2.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//	}
//
//	client.AgentsV2.Query().
//		Select(agentsv2.FieldStatus).
//		Scan(ctx, &v)
func (av *AgentsV2Query) Select(fields ...string) *AgentsV2Select {
	av.ctx.Fields = append(av.ctx.Fields, fields...)
	sbuild := &AgentsV2Select{AgentsV2Query: av}
	sbuild.label = agentsv2.Label
	sbuild.flds, sbuild.scan = &av.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AgentsV2Select configured with the given aggregations.
func (av *AgentsV2Query) Aggregate(fns ...AggregateFunc) *AgentsV2Select {
	return av.Select().Aggregate(fns...)
}

func (av *AgentsV2Query) prepareQuery(ctx context.Context) error {
	for _, inter := range av.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, av); err != nil {
				return err
			}
		}
	}
	for _, f := range av.ctx.Fields {
		if !agentsv2.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if av.path != nil {
		prev, err := av.path(ctx)
		if err != nil {
			return err
		}
		av.sql = prev
	}
	return nil
}

func (av *AgentsV2Query) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AgentsV2, error) {
	var (
		nodes = []*AgentsV2{}
		_spec = av.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AgentsV2).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AgentsV2{config: av.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, av.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (av *AgentsV2Query) sqlCount(ctx context.Context) (int, error) {
	_spec := av.querySpec()
	_spec.Node.Columns = av.ctx.Fields
	if len(av.ctx.Fields) > 0 {
		_spec.Unique = av.ctx.Unique != nil && *av.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, av.driver, _spec)
}

func (av *AgentsV2Query) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(agentsv2.Table, agentsv2.Columns, sqlgraph.NewFieldSpec(agentsv2.FieldID, field.TypeUUID))
	_spec.From = av.sql
	if unique := av.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if av.path != nil {
		_spec.Unique = true
	}
	if fields := av.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentsv2.FieldID)
		for i := range fields {
			if fields[i] != agentsv2.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := av.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := av.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := av.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := av.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (av *AgentsV2Query) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(av.driver.Dialect())
	t1 := builder.Table(agentsv2.Table)
	columns := av.ctx.Fields
	if len(columns) == 0 {
		columns = agentsv2.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if av.sql != nil {
		selector = av.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if av.ctx.Unique != nil && *av.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range av.predicates {
		p(selector)
	}
	for _, p := range av.order {
		p(selector)
	}
	if offset := av.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := av.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AgentsV2GroupBy is the group-by builder for AgentsV2 entities.
type AgentsV2GroupBy struct {
	selector
	build *AgentsV2Query
}

// Aggregate adds the given aggregation functions to the group-by query.
func (avb *AgentsV2GroupBy) Aggregate(fns ...AggregateFunc) *AgentsV2GroupBy {
	avb.fns = append(avb.fns, fns...)
	return avb
}

// Scan applies the selector query and scans the result into the given value.
func (avb *AgentsV2GroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, avb.build.ctx, ent.OpQueryGroupBy)
	if err := avb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentsV2Query, *AgentsV2GroupBy](ctx, avb.build, avb, avb.build.inters, v)
}

func (avb *AgentsV2GroupBy) sqlScan(ctx context.Context, root *AgentsV2Query, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(avb.fns))
	for _, fn := range avb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*avb.flds)+len(avb.fns))
		for _, f := range *avb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*avb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := avb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AgentsV2Select is the builder for selecting fields of AgentsV2 entities.
type AgentsV2Select struct {
	*AgentsV2Query
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (av *AgentsV2Select) Aggregate(fns ...AggregateFunc) *AgentsV2Select {
	av.fns = append(av.fns, fns...)
	return av
}

// Scan applies the selector query and scans the result into the given value.
func (av *AgentsV2Select) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, av.ctx, ent.OpQuerySelect)
	if err := av.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentsV2Query, *AgentsV2Select](ctx, av.AgentsV2Query, av, av.inters, v)
}

func (av *AgentsV2Select) sqlScan(ctx context.Context, root *AgentsV2Query, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(av.fns))
	for _, fn := range av.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*av.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := av.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
