// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shinobistack/gokakashi/ent/agents"
	"github.com/shinobistack/gokakashi/ent/agenttasks"
	"github.com/shinobistack/gokakashi/ent/predicate"
	"github.com/shinobistack/gokakashi/ent/scans"
)

// AgentTasksQuery is the builder for querying AgentTasks entities.
type AgentTasksQuery struct {
	config
	ctx        *QueryContext
	order      []agenttasks.OrderOption
	inters     []Interceptor
	predicates []predicate.AgentTasks
	withAgent  *AgentsQuery
	withScan   *ScansQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AgentTasksQuery builder.
func (atq *AgentTasksQuery) Where(ps ...predicate.AgentTasks) *AgentTasksQuery {
	atq.predicates = append(atq.predicates, ps...)
	return atq
}

// Limit the number of records to be returned by this query.
func (atq *AgentTasksQuery) Limit(limit int) *AgentTasksQuery {
	atq.ctx.Limit = &limit
	return atq
}

// Offset to start from.
func (atq *AgentTasksQuery) Offset(offset int) *AgentTasksQuery {
	atq.ctx.Offset = &offset
	return atq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (atq *AgentTasksQuery) Unique(unique bool) *AgentTasksQuery {
	atq.ctx.Unique = &unique
	return atq
}

// Order specifies how the records should be ordered.
func (atq *AgentTasksQuery) Order(o ...agenttasks.OrderOption) *AgentTasksQuery {
	atq.order = append(atq.order, o...)
	return atq
}

// QueryAgent chains the current query on the "agent" edge.
func (atq *AgentTasksQuery) QueryAgent() *AgentsQuery {
	query := (&AgentsClient{config: atq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := atq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := atq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agenttasks.Table, agenttasks.FieldID, selector),
			sqlgraph.To(agents.Table, agents.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, agenttasks.AgentTable, agenttasks.AgentColumn),
		)
		fromU = sqlgraph.SetNeighbors(atq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScan chains the current query on the "scan" edge.
func (atq *AgentTasksQuery) QueryScan() *ScansQuery {
	query := (&ScansClient{config: atq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := atq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := atq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agenttasks.Table, agenttasks.FieldID, selector),
			sqlgraph.To(scans.Table, scans.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, agenttasks.ScanTable, agenttasks.ScanColumn),
		)
		fromU = sqlgraph.SetNeighbors(atq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AgentTasks entity from the query.
// Returns a *NotFoundError when no AgentTasks was found.
func (atq *AgentTasksQuery) First(ctx context.Context) (*AgentTasks, error) {
	nodes, err := atq.Limit(1).All(setContextOp(ctx, atq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{agenttasks.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (atq *AgentTasksQuery) FirstX(ctx context.Context) *AgentTasks {
	node, err := atq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AgentTasks ID from the query.
// Returns a *NotFoundError when no AgentTasks ID was found.
func (atq *AgentTasksQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = atq.Limit(1).IDs(setContextOp(ctx, atq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{agenttasks.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (atq *AgentTasksQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := atq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AgentTasks entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AgentTasks entity is found.
// Returns a *NotFoundError when no AgentTasks entities are found.
func (atq *AgentTasksQuery) Only(ctx context.Context) (*AgentTasks, error) {
	nodes, err := atq.Limit(2).All(setContextOp(ctx, atq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{agenttasks.Label}
	default:
		return nil, &NotSingularError{agenttasks.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (atq *AgentTasksQuery) OnlyX(ctx context.Context) *AgentTasks {
	node, err := atq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AgentTasks ID in the query.
// Returns a *NotSingularError when more than one AgentTasks ID is found.
// Returns a *NotFoundError when no entities are found.
func (atq *AgentTasksQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = atq.Limit(2).IDs(setContextOp(ctx, atq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{agenttasks.Label}
	default:
		err = &NotSingularError{agenttasks.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (atq *AgentTasksQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := atq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AgentTasksSlice.
func (atq *AgentTasksQuery) All(ctx context.Context) ([]*AgentTasks, error) {
	ctx = setContextOp(ctx, atq.ctx, ent.OpQueryAll)
	if err := atq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AgentTasks, *AgentTasksQuery]()
	return withInterceptors[[]*AgentTasks](ctx, atq, qr, atq.inters)
}

// AllX is like All, but panics if an error occurs.
func (atq *AgentTasksQuery) AllX(ctx context.Context) []*AgentTasks {
	nodes, err := atq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AgentTasks IDs.
func (atq *AgentTasksQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if atq.ctx.Unique == nil && atq.path != nil {
		atq.Unique(true)
	}
	ctx = setContextOp(ctx, atq.ctx, ent.OpQueryIDs)
	if err = atq.Select(agenttasks.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (atq *AgentTasksQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := atq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (atq *AgentTasksQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, atq.ctx, ent.OpQueryCount)
	if err := atq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, atq, querierCount[*AgentTasksQuery](), atq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (atq *AgentTasksQuery) CountX(ctx context.Context) int {
	count, err := atq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (atq *AgentTasksQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, atq.ctx, ent.OpQueryExist)
	switch _, err := atq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (atq *AgentTasksQuery) ExistX(ctx context.Context) bool {
	exist, err := atq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AgentTasksQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (atq *AgentTasksQuery) Clone() *AgentTasksQuery {
	if atq == nil {
		return nil
	}
	return &AgentTasksQuery{
		config:     atq.config,
		ctx:        atq.ctx.Clone(),
		order:      append([]agenttasks.OrderOption{}, atq.order...),
		inters:     append([]Interceptor{}, atq.inters...),
		predicates: append([]predicate.AgentTasks{}, atq.predicates...),
		withAgent:  atq.withAgent.Clone(),
		withScan:   atq.withScan.Clone(),
		// clone intermediate query.
		sql:  atq.sql.Clone(),
		path: atq.path,
	}
}

// WithAgent tells the query-builder to eager-load the nodes that are connected to
// the "agent" edge. The optional arguments are used to configure the query builder of the edge.
func (atq *AgentTasksQuery) WithAgent(opts ...func(*AgentsQuery)) *AgentTasksQuery {
	query := (&AgentsClient{config: atq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	atq.withAgent = query
	return atq
}

// WithScan tells the query-builder to eager-load the nodes that are connected to
// the "scan" edge. The optional arguments are used to configure the query builder of the edge.
func (atq *AgentTasksQuery) WithScan(opts ...func(*ScansQuery)) *AgentTasksQuery {
	query := (&ScansClient{config: atq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	atq.withScan = query
	return atq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AgentID int `json:"agent_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AgentTasks.Query().
//		GroupBy(agenttasks.FieldAgentID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (atq *AgentTasksQuery) GroupBy(field string, fields ...string) *AgentTasksGroupBy {
	atq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AgentTasksGroupBy{build: atq}
	grbuild.flds = &atq.ctx.Fields
	grbuild.label = agenttasks.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AgentID int `json:"agent_id,omitempty"`
//	}
//
//	client.AgentTasks.Query().
//		Select(agenttasks.FieldAgentID).
//		Scan(ctx, &v)
func (atq *AgentTasksQuery) Select(fields ...string) *AgentTasksSelect {
	atq.ctx.Fields = append(atq.ctx.Fields, fields...)
	sbuild := &AgentTasksSelect{AgentTasksQuery: atq}
	sbuild.label = agenttasks.Label
	sbuild.flds, sbuild.scan = &atq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AgentTasksSelect configured with the given aggregations.
func (atq *AgentTasksQuery) Aggregate(fns ...AggregateFunc) *AgentTasksSelect {
	return atq.Select().Aggregate(fns...)
}

func (atq *AgentTasksQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range atq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, atq); err != nil {
				return err
			}
		}
	}
	for _, f := range atq.ctx.Fields {
		if !agenttasks.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if atq.path != nil {
		prev, err := atq.path(ctx)
		if err != nil {
			return err
		}
		atq.sql = prev
	}
	return nil
}

func (atq *AgentTasksQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AgentTasks, error) {
	var (
		nodes       = []*AgentTasks{}
		_spec       = atq.querySpec()
		loadedTypes = [2]bool{
			atq.withAgent != nil,
			atq.withScan != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AgentTasks).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AgentTasks{config: atq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, atq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := atq.withAgent; query != nil {
		if err := atq.loadAgent(ctx, query, nodes, nil,
			func(n *AgentTasks, e *Agents) { n.Edges.Agent = e }); err != nil {
			return nil, err
		}
	}
	if query := atq.withScan; query != nil {
		if err := atq.loadScan(ctx, query, nodes, nil,
			func(n *AgentTasks, e *Scans) { n.Edges.Scan = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (atq *AgentTasksQuery) loadAgent(ctx context.Context, query *AgentsQuery, nodes []*AgentTasks, init func(*AgentTasks), assign func(*AgentTasks, *Agents)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AgentTasks)
	for i := range nodes {
		fk := nodes[i].AgentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agents.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (atq *AgentTasksQuery) loadScan(ctx context.Context, query *ScansQuery, nodes []*AgentTasks, init func(*AgentTasks), assign func(*AgentTasks, *Scans)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AgentTasks)
	for i := range nodes {
		fk := nodes[i].ScanID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(scans.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "scan_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (atq *AgentTasksQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := atq.querySpec()
	_spec.Node.Columns = atq.ctx.Fields
	if len(atq.ctx.Fields) > 0 {
		_spec.Unique = atq.ctx.Unique != nil && *atq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, atq.driver, _spec)
}

func (atq *AgentTasksQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(agenttasks.Table, agenttasks.Columns, sqlgraph.NewFieldSpec(agenttasks.FieldID, field.TypeUUID))
	_spec.From = atq.sql
	if unique := atq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if atq.path != nil {
		_spec.Unique = true
	}
	if fields := atq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agenttasks.FieldID)
		for i := range fields {
			if fields[i] != agenttasks.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if atq.withAgent != nil {
			_spec.Node.AddColumnOnce(agenttasks.FieldAgentID)
		}
		if atq.withScan != nil {
			_spec.Node.AddColumnOnce(agenttasks.FieldScanID)
		}
	}
	if ps := atq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := atq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := atq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := atq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (atq *AgentTasksQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(atq.driver.Dialect())
	t1 := builder.Table(agenttasks.Table)
	columns := atq.ctx.Fields
	if len(columns) == 0 {
		columns = agenttasks.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if atq.sql != nil {
		selector = atq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if atq.ctx.Unique != nil && *atq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range atq.predicates {
		p(selector)
	}
	for _, p := range atq.order {
		p(selector)
	}
	if offset := atq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := atq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AgentTasksGroupBy is the group-by builder for AgentTasks entities.
type AgentTasksGroupBy struct {
	selector
	build *AgentTasksQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (atgb *AgentTasksGroupBy) Aggregate(fns ...AggregateFunc) *AgentTasksGroupBy {
	atgb.fns = append(atgb.fns, fns...)
	return atgb
}

// Scan applies the selector query and scans the result into the given value.
func (atgb *AgentTasksGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, atgb.build.ctx, ent.OpQueryGroupBy)
	if err := atgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentTasksQuery, *AgentTasksGroupBy](ctx, atgb.build, atgb, atgb.build.inters, v)
}

func (atgb *AgentTasksGroupBy) sqlScan(ctx context.Context, root *AgentTasksQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(atgb.fns))
	for _, fn := range atgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*atgb.flds)+len(atgb.fns))
		for _, f := range *atgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*atgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := atgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AgentTasksSelect is the builder for selecting fields of AgentTasks entities.
type AgentTasksSelect struct {
	*AgentTasksQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ats *AgentTasksSelect) Aggregate(fns ...AggregateFunc) *AgentTasksSelect {
	ats.fns = append(ats.fns, fns...)
	return ats
}

// Scan applies the selector query and scans the result into the given value.
func (ats *AgentTasksSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ats.ctx, ent.OpQuerySelect)
	if err := ats.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentTasksQuery, *AgentTasksSelect](ctx, ats.AgentTasksQuery, ats, ats.inters, v)
}

func (ats *AgentTasksSelect) sqlScan(ctx context.Context, root *AgentTasksQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ats.fns))
	for _, fn := range ats.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ats.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
