// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/shinobistack/gokakashi/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shinobistack/gokakashi/ent/integrations"
	"github.com/shinobistack/gokakashi/ent/integrationtype"
	"github.com/shinobistack/gokakashi/ent/policies"
	"github.com/shinobistack/gokakashi/ent/policylabels"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// IntegrationType is the client for interacting with the IntegrationType builders.
	IntegrationType *IntegrationTypeClient
	// Integrations is the client for interacting with the Integrations builders.
	Integrations *IntegrationsClient
	// Policies is the client for interacting with the Policies builders.
	Policies *PoliciesClient
	// PolicyLabels is the client for interacting with the PolicyLabels builders.
	PolicyLabels *PolicyLabelsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.IntegrationType = NewIntegrationTypeClient(c.config)
	c.Integrations = NewIntegrationsClient(c.config)
	c.Policies = NewPoliciesClient(c.config)
	c.PolicyLabels = NewPolicyLabelsClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		IntegrationType: NewIntegrationTypeClient(cfg),
		Integrations:    NewIntegrationsClient(cfg),
		Policies:        NewPoliciesClient(cfg),
		PolicyLabels:    NewPolicyLabelsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		IntegrationType: NewIntegrationTypeClient(cfg),
		Integrations:    NewIntegrationsClient(cfg),
		Policies:        NewPoliciesClient(cfg),
		PolicyLabels:    NewPolicyLabelsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		IntegrationType.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.IntegrationType.Use(hooks...)
	c.Integrations.Use(hooks...)
	c.Policies.Use(hooks...)
	c.PolicyLabels.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.IntegrationType.Intercept(interceptors...)
	c.Integrations.Intercept(interceptors...)
	c.Policies.Intercept(interceptors...)
	c.PolicyLabels.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *IntegrationTypeMutation:
		return c.IntegrationType.mutate(ctx, m)
	case *IntegrationsMutation:
		return c.Integrations.mutate(ctx, m)
	case *PoliciesMutation:
		return c.Policies.mutate(ctx, m)
	case *PolicyLabelsMutation:
		return c.PolicyLabels.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// IntegrationTypeClient is a client for the IntegrationType schema.
type IntegrationTypeClient struct {
	config
}

// NewIntegrationTypeClient returns a client for the IntegrationType from the given config.
func NewIntegrationTypeClient(c config) *IntegrationTypeClient {
	return &IntegrationTypeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `integrationtype.Hooks(f(g(h())))`.
func (c *IntegrationTypeClient) Use(hooks ...Hook) {
	c.hooks.IntegrationType = append(c.hooks.IntegrationType, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `integrationtype.Intercept(f(g(h())))`.
func (c *IntegrationTypeClient) Intercept(interceptors ...Interceptor) {
	c.inters.IntegrationType = append(c.inters.IntegrationType, interceptors...)
}

// Create returns a builder for creating a IntegrationType entity.
func (c *IntegrationTypeClient) Create() *IntegrationTypeCreate {
	mutation := newIntegrationTypeMutation(c.config, OpCreate)
	return &IntegrationTypeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of IntegrationType entities.
func (c *IntegrationTypeClient) CreateBulk(builders ...*IntegrationTypeCreate) *IntegrationTypeCreateBulk {
	return &IntegrationTypeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IntegrationTypeClient) MapCreateBulk(slice any, setFunc func(*IntegrationTypeCreate, int)) *IntegrationTypeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IntegrationTypeCreateBulk{err: fmt.Errorf("calling to IntegrationTypeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IntegrationTypeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IntegrationTypeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for IntegrationType.
func (c *IntegrationTypeClient) Update() *IntegrationTypeUpdate {
	mutation := newIntegrationTypeMutation(c.config, OpUpdate)
	return &IntegrationTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IntegrationTypeClient) UpdateOne(it *IntegrationType) *IntegrationTypeUpdateOne {
	mutation := newIntegrationTypeMutation(c.config, OpUpdateOne, withIntegrationType(it))
	return &IntegrationTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IntegrationTypeClient) UpdateOneID(id string) *IntegrationTypeUpdateOne {
	mutation := newIntegrationTypeMutation(c.config, OpUpdateOne, withIntegrationTypeID(id))
	return &IntegrationTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for IntegrationType.
func (c *IntegrationTypeClient) Delete() *IntegrationTypeDelete {
	mutation := newIntegrationTypeMutation(c.config, OpDelete)
	return &IntegrationTypeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IntegrationTypeClient) DeleteOne(it *IntegrationType) *IntegrationTypeDeleteOne {
	return c.DeleteOneID(it.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IntegrationTypeClient) DeleteOneID(id string) *IntegrationTypeDeleteOne {
	builder := c.Delete().Where(integrationtype.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IntegrationTypeDeleteOne{builder}
}

// Query returns a query builder for IntegrationType.
func (c *IntegrationTypeClient) Query() *IntegrationTypeQuery {
	return &IntegrationTypeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIntegrationType},
		inters: c.Interceptors(),
	}
}

// Get returns a IntegrationType entity by its id.
func (c *IntegrationTypeClient) Get(ctx context.Context, id string) (*IntegrationType, error) {
	return c.Query().Where(integrationtype.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IntegrationTypeClient) GetX(ctx context.Context, id string) *IntegrationType {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryIntegrations queries the integrations edge of a IntegrationType.
func (c *IntegrationTypeClient) QueryIntegrations(it *IntegrationType) *IntegrationsQuery {
	query := (&IntegrationsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := it.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(integrationtype.Table, integrationtype.FieldID, id),
			sqlgraph.To(integrations.Table, integrations.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, integrationtype.IntegrationsTable, integrationtype.IntegrationsColumn),
		)
		fromV = sqlgraph.Neighbors(it.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *IntegrationTypeClient) Hooks() []Hook {
	return c.hooks.IntegrationType
}

// Interceptors returns the client interceptors.
func (c *IntegrationTypeClient) Interceptors() []Interceptor {
	return c.inters.IntegrationType
}

func (c *IntegrationTypeClient) mutate(ctx context.Context, m *IntegrationTypeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IntegrationTypeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IntegrationTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IntegrationTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IntegrationTypeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown IntegrationType mutation op: %q", m.Op())
	}
}

// IntegrationsClient is a client for the Integrations schema.
type IntegrationsClient struct {
	config
}

// NewIntegrationsClient returns a client for the Integrations from the given config.
func NewIntegrationsClient(c config) *IntegrationsClient {
	return &IntegrationsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `integrations.Hooks(f(g(h())))`.
func (c *IntegrationsClient) Use(hooks ...Hook) {
	c.hooks.Integrations = append(c.hooks.Integrations, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `integrations.Intercept(f(g(h())))`.
func (c *IntegrationsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Integrations = append(c.inters.Integrations, interceptors...)
}

// Create returns a builder for creating a Integrations entity.
func (c *IntegrationsClient) Create() *IntegrationsCreate {
	mutation := newIntegrationsMutation(c.config, OpCreate)
	return &IntegrationsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Integrations entities.
func (c *IntegrationsClient) CreateBulk(builders ...*IntegrationsCreate) *IntegrationsCreateBulk {
	return &IntegrationsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IntegrationsClient) MapCreateBulk(slice any, setFunc func(*IntegrationsCreate, int)) *IntegrationsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IntegrationsCreateBulk{err: fmt.Errorf("calling to IntegrationsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IntegrationsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IntegrationsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Integrations.
func (c *IntegrationsClient) Update() *IntegrationsUpdate {
	mutation := newIntegrationsMutation(c.config, OpUpdate)
	return &IntegrationsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IntegrationsClient) UpdateOne(i *Integrations) *IntegrationsUpdateOne {
	mutation := newIntegrationsMutation(c.config, OpUpdateOne, withIntegrations(i))
	return &IntegrationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IntegrationsClient) UpdateOneID(id uuid.UUID) *IntegrationsUpdateOne {
	mutation := newIntegrationsMutation(c.config, OpUpdateOne, withIntegrationsID(id))
	return &IntegrationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Integrations.
func (c *IntegrationsClient) Delete() *IntegrationsDelete {
	mutation := newIntegrationsMutation(c.config, OpDelete)
	return &IntegrationsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IntegrationsClient) DeleteOne(i *Integrations) *IntegrationsDeleteOne {
	return c.DeleteOneID(i.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IntegrationsClient) DeleteOneID(id uuid.UUID) *IntegrationsDeleteOne {
	builder := c.Delete().Where(integrations.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IntegrationsDeleteOne{builder}
}

// Query returns a query builder for Integrations.
func (c *IntegrationsClient) Query() *IntegrationsQuery {
	return &IntegrationsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIntegrations},
		inters: c.Interceptors(),
	}
}

// Get returns a Integrations entity by its id.
func (c *IntegrationsClient) Get(ctx context.Context, id uuid.UUID) (*Integrations, error) {
	return c.Query().Where(integrations.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IntegrationsClient) GetX(ctx context.Context, id uuid.UUID) *Integrations {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *IntegrationsClient) Hooks() []Hook {
	return c.hooks.Integrations
}

// Interceptors returns the client interceptors.
func (c *IntegrationsClient) Interceptors() []Interceptor {
	return c.inters.Integrations
}

func (c *IntegrationsClient) mutate(ctx context.Context, m *IntegrationsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IntegrationsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IntegrationsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IntegrationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IntegrationsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Integrations mutation op: %q", m.Op())
	}
}

// PoliciesClient is a client for the Policies schema.
type PoliciesClient struct {
	config
}

// NewPoliciesClient returns a client for the Policies from the given config.
func NewPoliciesClient(c config) *PoliciesClient {
	return &PoliciesClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `policies.Hooks(f(g(h())))`.
func (c *PoliciesClient) Use(hooks ...Hook) {
	c.hooks.Policies = append(c.hooks.Policies, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `policies.Intercept(f(g(h())))`.
func (c *PoliciesClient) Intercept(interceptors ...Interceptor) {
	c.inters.Policies = append(c.inters.Policies, interceptors...)
}

// Create returns a builder for creating a Policies entity.
func (c *PoliciesClient) Create() *PoliciesCreate {
	mutation := newPoliciesMutation(c.config, OpCreate)
	return &PoliciesCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Policies entities.
func (c *PoliciesClient) CreateBulk(builders ...*PoliciesCreate) *PoliciesCreateBulk {
	return &PoliciesCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PoliciesClient) MapCreateBulk(slice any, setFunc func(*PoliciesCreate, int)) *PoliciesCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PoliciesCreateBulk{err: fmt.Errorf("calling to PoliciesClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PoliciesCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PoliciesCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Policies.
func (c *PoliciesClient) Update() *PoliciesUpdate {
	mutation := newPoliciesMutation(c.config, OpUpdate)
	return &PoliciesUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PoliciesClient) UpdateOne(po *Policies) *PoliciesUpdateOne {
	mutation := newPoliciesMutation(c.config, OpUpdateOne, withPolicies(po))
	return &PoliciesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PoliciesClient) UpdateOneID(id uuid.UUID) *PoliciesUpdateOne {
	mutation := newPoliciesMutation(c.config, OpUpdateOne, withPoliciesID(id))
	return &PoliciesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Policies.
func (c *PoliciesClient) Delete() *PoliciesDelete {
	mutation := newPoliciesMutation(c.config, OpDelete)
	return &PoliciesDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PoliciesClient) DeleteOne(po *Policies) *PoliciesDeleteOne {
	return c.DeleteOneID(po.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PoliciesClient) DeleteOneID(id uuid.UUID) *PoliciesDeleteOne {
	builder := c.Delete().Where(policies.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PoliciesDeleteOne{builder}
}

// Query returns a query builder for Policies.
func (c *PoliciesClient) Query() *PoliciesQuery {
	return &PoliciesQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePolicies},
		inters: c.Interceptors(),
	}
}

// Get returns a Policies entity by its id.
func (c *PoliciesClient) Get(ctx context.Context, id uuid.UUID) (*Policies, error) {
	return c.Query().Where(policies.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PoliciesClient) GetX(ctx context.Context, id uuid.UUID) *Policies {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPolicyLabels queries the policy_labels edge of a Policies.
func (c *PoliciesClient) QueryPolicyLabels(po *Policies) *PolicyLabelsQuery {
	query := (&PolicyLabelsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := po.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(policies.Table, policies.FieldID, id),
			sqlgraph.To(policylabels.Table, policylabels.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, policies.PolicyLabelsTable, policies.PolicyLabelsColumn),
		)
		fromV = sqlgraph.Neighbors(po.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PoliciesClient) Hooks() []Hook {
	return c.hooks.Policies
}

// Interceptors returns the client interceptors.
func (c *PoliciesClient) Interceptors() []Interceptor {
	return c.inters.Policies
}

func (c *PoliciesClient) mutate(ctx context.Context, m *PoliciesMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PoliciesCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PoliciesUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PoliciesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PoliciesDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Policies mutation op: %q", m.Op())
	}
}

// PolicyLabelsClient is a client for the PolicyLabels schema.
type PolicyLabelsClient struct {
	config
}

// NewPolicyLabelsClient returns a client for the PolicyLabels from the given config.
func NewPolicyLabelsClient(c config) *PolicyLabelsClient {
	return &PolicyLabelsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `policylabels.Hooks(f(g(h())))`.
func (c *PolicyLabelsClient) Use(hooks ...Hook) {
	c.hooks.PolicyLabels = append(c.hooks.PolicyLabels, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `policylabels.Intercept(f(g(h())))`.
func (c *PolicyLabelsClient) Intercept(interceptors ...Interceptor) {
	c.inters.PolicyLabels = append(c.inters.PolicyLabels, interceptors...)
}

// Create returns a builder for creating a PolicyLabels entity.
func (c *PolicyLabelsClient) Create() *PolicyLabelsCreate {
	mutation := newPolicyLabelsMutation(c.config, OpCreate)
	return &PolicyLabelsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PolicyLabels entities.
func (c *PolicyLabelsClient) CreateBulk(builders ...*PolicyLabelsCreate) *PolicyLabelsCreateBulk {
	return &PolicyLabelsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PolicyLabelsClient) MapCreateBulk(slice any, setFunc func(*PolicyLabelsCreate, int)) *PolicyLabelsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PolicyLabelsCreateBulk{err: fmt.Errorf("calling to PolicyLabelsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PolicyLabelsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PolicyLabelsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PolicyLabels.
func (c *PolicyLabelsClient) Update() *PolicyLabelsUpdate {
	mutation := newPolicyLabelsMutation(c.config, OpUpdate)
	return &PolicyLabelsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PolicyLabelsClient) UpdateOne(pl *PolicyLabels) *PolicyLabelsUpdateOne {
	mutation := newPolicyLabelsMutation(c.config, OpUpdateOne, withPolicyLabels(pl))
	return &PolicyLabelsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PolicyLabelsClient) UpdateOneID(id int) *PolicyLabelsUpdateOne {
	mutation := newPolicyLabelsMutation(c.config, OpUpdateOne, withPolicyLabelsID(id))
	return &PolicyLabelsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PolicyLabels.
func (c *PolicyLabelsClient) Delete() *PolicyLabelsDelete {
	mutation := newPolicyLabelsMutation(c.config, OpDelete)
	return &PolicyLabelsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PolicyLabelsClient) DeleteOne(pl *PolicyLabels) *PolicyLabelsDeleteOne {
	return c.DeleteOneID(pl.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PolicyLabelsClient) DeleteOneID(id int) *PolicyLabelsDeleteOne {
	builder := c.Delete().Where(policylabels.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PolicyLabelsDeleteOne{builder}
}

// Query returns a query builder for PolicyLabels.
func (c *PolicyLabelsClient) Query() *PolicyLabelsQuery {
	return &PolicyLabelsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePolicyLabels},
		inters: c.Interceptors(),
	}
}

// Get returns a PolicyLabels entity by its id.
func (c *PolicyLabelsClient) Get(ctx context.Context, id int) (*PolicyLabels, error) {
	return c.Query().Where(policylabels.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PolicyLabelsClient) GetX(ctx context.Context, id int) *PolicyLabels {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPolicy queries the policy edge of a PolicyLabels.
func (c *PolicyLabelsClient) QueryPolicy(pl *PolicyLabels) *PoliciesQuery {
	query := (&PoliciesClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(policylabels.Table, policylabels.FieldID, id),
			sqlgraph.To(policies.Table, policies.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, policylabels.PolicyTable, policylabels.PolicyColumn),
		)
		fromV = sqlgraph.Neighbors(pl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PolicyLabelsClient) Hooks() []Hook {
	return c.hooks.PolicyLabels
}

// Interceptors returns the client interceptors.
func (c *PolicyLabelsClient) Interceptors() []Interceptor {
	return c.inters.PolicyLabels
}

func (c *PolicyLabelsClient) mutate(ctx context.Context, m *PolicyLabelsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PolicyLabelsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PolicyLabelsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PolicyLabelsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PolicyLabelsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PolicyLabels mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		IntegrationType, Integrations, Policies, PolicyLabels []ent.Hook
	}
	inters struct {
		IntegrationType, Integrations, Policies, PolicyLabels []ent.Interceptor
	}
)
