// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/shinobistack/gokakashi/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shinobistack/gokakashi/ent/integrations"
	"github.com/shinobistack/gokakashi/ent/integrationtype"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// IntegrationType is the client for interacting with the IntegrationType builders.
	IntegrationType *IntegrationTypeClient
	// Integrations is the client for interacting with the Integrations builders.
	Integrations *IntegrationsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.IntegrationType = NewIntegrationTypeClient(c.config)
	c.Integrations = NewIntegrationsClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		IntegrationType: NewIntegrationTypeClient(cfg),
		Integrations:    NewIntegrationsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		IntegrationType: NewIntegrationTypeClient(cfg),
		Integrations:    NewIntegrationsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		IntegrationType.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.IntegrationType.Use(hooks...)
	c.Integrations.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.IntegrationType.Intercept(interceptors...)
	c.Integrations.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *IntegrationTypeMutation:
		return c.IntegrationType.mutate(ctx, m)
	case *IntegrationsMutation:
		return c.Integrations.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// IntegrationTypeClient is a client for the IntegrationType schema.
type IntegrationTypeClient struct {
	config
}

// NewIntegrationTypeClient returns a client for the IntegrationType from the given config.
func NewIntegrationTypeClient(c config) *IntegrationTypeClient {
	return &IntegrationTypeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `integrationtype.Hooks(f(g(h())))`.
func (c *IntegrationTypeClient) Use(hooks ...Hook) {
	c.hooks.IntegrationType = append(c.hooks.IntegrationType, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `integrationtype.Intercept(f(g(h())))`.
func (c *IntegrationTypeClient) Intercept(interceptors ...Interceptor) {
	c.inters.IntegrationType = append(c.inters.IntegrationType, interceptors...)
}

// Create returns a builder for creating a IntegrationType entity.
func (c *IntegrationTypeClient) Create() *IntegrationTypeCreate {
	mutation := newIntegrationTypeMutation(c.config, OpCreate)
	return &IntegrationTypeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of IntegrationType entities.
func (c *IntegrationTypeClient) CreateBulk(builders ...*IntegrationTypeCreate) *IntegrationTypeCreateBulk {
	return &IntegrationTypeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IntegrationTypeClient) MapCreateBulk(slice any, setFunc func(*IntegrationTypeCreate, int)) *IntegrationTypeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IntegrationTypeCreateBulk{err: fmt.Errorf("calling to IntegrationTypeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IntegrationTypeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IntegrationTypeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for IntegrationType.
func (c *IntegrationTypeClient) Update() *IntegrationTypeUpdate {
	mutation := newIntegrationTypeMutation(c.config, OpUpdate)
	return &IntegrationTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IntegrationTypeClient) UpdateOne(it *IntegrationType) *IntegrationTypeUpdateOne {
	mutation := newIntegrationTypeMutation(c.config, OpUpdateOne, withIntegrationType(it))
	return &IntegrationTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IntegrationTypeClient) UpdateOneID(id string) *IntegrationTypeUpdateOne {
	mutation := newIntegrationTypeMutation(c.config, OpUpdateOne, withIntegrationTypeID(id))
	return &IntegrationTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for IntegrationType.
func (c *IntegrationTypeClient) Delete() *IntegrationTypeDelete {
	mutation := newIntegrationTypeMutation(c.config, OpDelete)
	return &IntegrationTypeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IntegrationTypeClient) DeleteOne(it *IntegrationType) *IntegrationTypeDeleteOne {
	return c.DeleteOneID(it.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IntegrationTypeClient) DeleteOneID(id string) *IntegrationTypeDeleteOne {
	builder := c.Delete().Where(integrationtype.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IntegrationTypeDeleteOne{builder}
}

// Query returns a query builder for IntegrationType.
func (c *IntegrationTypeClient) Query() *IntegrationTypeQuery {
	return &IntegrationTypeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIntegrationType},
		inters: c.Interceptors(),
	}
}

// Get returns a IntegrationType entity by its id.
func (c *IntegrationTypeClient) Get(ctx context.Context, id string) (*IntegrationType, error) {
	return c.Query().Where(integrationtype.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IntegrationTypeClient) GetX(ctx context.Context, id string) *IntegrationType {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryIntegrations queries the integrations edge of a IntegrationType.
func (c *IntegrationTypeClient) QueryIntegrations(it *IntegrationType) *IntegrationsQuery {
	query := (&IntegrationsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := it.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(integrationtype.Table, integrationtype.FieldID, id),
			sqlgraph.To(integrations.Table, integrations.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, integrationtype.IntegrationsTable, integrationtype.IntegrationsColumn),
		)
		fromV = sqlgraph.Neighbors(it.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *IntegrationTypeClient) Hooks() []Hook {
	return c.hooks.IntegrationType
}

// Interceptors returns the client interceptors.
func (c *IntegrationTypeClient) Interceptors() []Interceptor {
	return c.inters.IntegrationType
}

func (c *IntegrationTypeClient) mutate(ctx context.Context, m *IntegrationTypeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IntegrationTypeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IntegrationTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IntegrationTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IntegrationTypeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown IntegrationType mutation op: %q", m.Op())
	}
}

// IntegrationsClient is a client for the Integrations schema.
type IntegrationsClient struct {
	config
}

// NewIntegrationsClient returns a client for the Integrations from the given config.
func NewIntegrationsClient(c config) *IntegrationsClient {
	return &IntegrationsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `integrations.Hooks(f(g(h())))`.
func (c *IntegrationsClient) Use(hooks ...Hook) {
	c.hooks.Integrations = append(c.hooks.Integrations, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `integrations.Intercept(f(g(h())))`.
func (c *IntegrationsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Integrations = append(c.inters.Integrations, interceptors...)
}

// Create returns a builder for creating a Integrations entity.
func (c *IntegrationsClient) Create() *IntegrationsCreate {
	mutation := newIntegrationsMutation(c.config, OpCreate)
	return &IntegrationsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Integrations entities.
func (c *IntegrationsClient) CreateBulk(builders ...*IntegrationsCreate) *IntegrationsCreateBulk {
	return &IntegrationsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IntegrationsClient) MapCreateBulk(slice any, setFunc func(*IntegrationsCreate, int)) *IntegrationsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IntegrationsCreateBulk{err: fmt.Errorf("calling to IntegrationsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IntegrationsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IntegrationsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Integrations.
func (c *IntegrationsClient) Update() *IntegrationsUpdate {
	mutation := newIntegrationsMutation(c.config, OpUpdate)
	return &IntegrationsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IntegrationsClient) UpdateOne(i *Integrations) *IntegrationsUpdateOne {
	mutation := newIntegrationsMutation(c.config, OpUpdateOne, withIntegrations(i))
	return &IntegrationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IntegrationsClient) UpdateOneID(id uuid.UUID) *IntegrationsUpdateOne {
	mutation := newIntegrationsMutation(c.config, OpUpdateOne, withIntegrationsID(id))
	return &IntegrationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Integrations.
func (c *IntegrationsClient) Delete() *IntegrationsDelete {
	mutation := newIntegrationsMutation(c.config, OpDelete)
	return &IntegrationsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IntegrationsClient) DeleteOne(i *Integrations) *IntegrationsDeleteOne {
	return c.DeleteOneID(i.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IntegrationsClient) DeleteOneID(id uuid.UUID) *IntegrationsDeleteOne {
	builder := c.Delete().Where(integrations.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IntegrationsDeleteOne{builder}
}

// Query returns a query builder for Integrations.
func (c *IntegrationsClient) Query() *IntegrationsQuery {
	return &IntegrationsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIntegrations},
		inters: c.Interceptors(),
	}
}

// Get returns a Integrations entity by its id.
func (c *IntegrationsClient) Get(ctx context.Context, id uuid.UUID) (*Integrations, error) {
	return c.Query().Where(integrations.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IntegrationsClient) GetX(ctx context.Context, id uuid.UUID) *Integrations {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *IntegrationsClient) Hooks() []Hook {
	return c.hooks.Integrations
}

// Interceptors returns the client interceptors.
func (c *IntegrationsClient) Interceptors() []Interceptor {
	return c.inters.Integrations
}

func (c *IntegrationsClient) mutate(ctx context.Context, m *IntegrationsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IntegrationsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IntegrationsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IntegrationsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IntegrationsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Integrations mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		IntegrationType, Integrations []ent.Hook
	}
	inters struct {
		IntegrationType, Integrations []ent.Interceptor
	}
)
