// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shinobistack/gokakashi/ent/policylabels"
	"github.com/shinobistack/gokakashi/ent/predicate"
)

// PolicyLabelsDelete is the builder for deleting a PolicyLabels entity.
type PolicyLabelsDelete struct {
	config
	hooks    []Hook
	mutation *PolicyLabelsMutation
}

// Where appends a list predicates to the PolicyLabelsDelete builder.
func (pld *PolicyLabelsDelete) Where(ps ...predicate.PolicyLabels) *PolicyLabelsDelete {
	pld.mutation.Where(ps...)
	return pld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pld *PolicyLabelsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pld.sqlExec, pld.mutation, pld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pld *PolicyLabelsDelete) ExecX(ctx context.Context) int {
	n, err := pld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pld *PolicyLabelsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(policylabels.Table, sqlgraph.NewFieldSpec(policylabels.FieldID, field.TypeInt))
	if ps := pld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pld.mutation.done = true
	return affected, err
}

// PolicyLabelsDeleteOne is the builder for deleting a single PolicyLabels entity.
type PolicyLabelsDeleteOne struct {
	pld *PolicyLabelsDelete
}

// Where appends a list predicates to the PolicyLabelsDelete builder.
func (pldo *PolicyLabelsDeleteOne) Where(ps ...predicate.PolicyLabels) *PolicyLabelsDeleteOne {
	pldo.pld.mutation.Where(ps...)
	return pldo
}

// Exec executes the deletion query.
func (pldo *PolicyLabelsDeleteOne) Exec(ctx context.Context) error {
	n, err := pldo.pld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{policylabels.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pldo *PolicyLabelsDeleteOne) ExecX(ctx context.Context) {
	if err := pldo.Exec(ctx); err != nil {
		panic(err)
	}
}
