// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shinobistack/gokakashi/ent/policies"
	"github.com/shinobistack/gokakashi/ent/policylabels"
	"github.com/shinobistack/gokakashi/ent/predicate"
)

// PolicyLabelsQuery is the builder for querying PolicyLabels entities.
type PolicyLabelsQuery struct {
	config
	ctx        *QueryContext
	order      []policylabels.OrderOption
	inters     []Interceptor
	predicates []predicate.PolicyLabels
	withPolicy *PoliciesQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PolicyLabelsQuery builder.
func (plq *PolicyLabelsQuery) Where(ps ...predicate.PolicyLabels) *PolicyLabelsQuery {
	plq.predicates = append(plq.predicates, ps...)
	return plq
}

// Limit the number of records to be returned by this query.
func (plq *PolicyLabelsQuery) Limit(limit int) *PolicyLabelsQuery {
	plq.ctx.Limit = &limit
	return plq
}

// Offset to start from.
func (plq *PolicyLabelsQuery) Offset(offset int) *PolicyLabelsQuery {
	plq.ctx.Offset = &offset
	return plq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (plq *PolicyLabelsQuery) Unique(unique bool) *PolicyLabelsQuery {
	plq.ctx.Unique = &unique
	return plq
}

// Order specifies how the records should be ordered.
func (plq *PolicyLabelsQuery) Order(o ...policylabels.OrderOption) *PolicyLabelsQuery {
	plq.order = append(plq.order, o...)
	return plq
}

// QueryPolicy chains the current query on the "policy" edge.
func (plq *PolicyLabelsQuery) QueryPolicy() *PoliciesQuery {
	query := (&PoliciesClient{config: plq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := plq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := plq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(policylabels.Table, policylabels.FieldID, selector),
			sqlgraph.To(policies.Table, policies.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, policylabels.PolicyTable, policylabels.PolicyColumn),
		)
		fromU = sqlgraph.SetNeighbors(plq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PolicyLabels entity from the query.
// Returns a *NotFoundError when no PolicyLabels was found.
func (plq *PolicyLabelsQuery) First(ctx context.Context) (*PolicyLabels, error) {
	nodes, err := plq.Limit(1).All(setContextOp(ctx, plq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{policylabels.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (plq *PolicyLabelsQuery) FirstX(ctx context.Context) *PolicyLabels {
	node, err := plq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PolicyLabels ID from the query.
// Returns a *NotFoundError when no PolicyLabels ID was found.
func (plq *PolicyLabelsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = plq.Limit(1).IDs(setContextOp(ctx, plq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{policylabels.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (plq *PolicyLabelsQuery) FirstIDX(ctx context.Context) int {
	id, err := plq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PolicyLabels entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PolicyLabels entity is found.
// Returns a *NotFoundError when no PolicyLabels entities are found.
func (plq *PolicyLabelsQuery) Only(ctx context.Context) (*PolicyLabels, error) {
	nodes, err := plq.Limit(2).All(setContextOp(ctx, plq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{policylabels.Label}
	default:
		return nil, &NotSingularError{policylabels.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (plq *PolicyLabelsQuery) OnlyX(ctx context.Context) *PolicyLabels {
	node, err := plq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PolicyLabels ID in the query.
// Returns a *NotSingularError when more than one PolicyLabels ID is found.
// Returns a *NotFoundError when no entities are found.
func (plq *PolicyLabelsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = plq.Limit(2).IDs(setContextOp(ctx, plq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{policylabels.Label}
	default:
		err = &NotSingularError{policylabels.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (plq *PolicyLabelsQuery) OnlyIDX(ctx context.Context) int {
	id, err := plq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PolicyLabelsSlice.
func (plq *PolicyLabelsQuery) All(ctx context.Context) ([]*PolicyLabels, error) {
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryAll)
	if err := plq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PolicyLabels, *PolicyLabelsQuery]()
	return withInterceptors[[]*PolicyLabels](ctx, plq, qr, plq.inters)
}

// AllX is like All, but panics if an error occurs.
func (plq *PolicyLabelsQuery) AllX(ctx context.Context) []*PolicyLabels {
	nodes, err := plq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PolicyLabels IDs.
func (plq *PolicyLabelsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if plq.ctx.Unique == nil && plq.path != nil {
		plq.Unique(true)
	}
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryIDs)
	if err = plq.Select(policylabels.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (plq *PolicyLabelsQuery) IDsX(ctx context.Context) []int {
	ids, err := plq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (plq *PolicyLabelsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryCount)
	if err := plq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, plq, querierCount[*PolicyLabelsQuery](), plq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (plq *PolicyLabelsQuery) CountX(ctx context.Context) int {
	count, err := plq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (plq *PolicyLabelsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, plq.ctx, ent.OpQueryExist)
	switch _, err := plq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (plq *PolicyLabelsQuery) ExistX(ctx context.Context) bool {
	exist, err := plq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PolicyLabelsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (plq *PolicyLabelsQuery) Clone() *PolicyLabelsQuery {
	if plq == nil {
		return nil
	}
	return &PolicyLabelsQuery{
		config:     plq.config,
		ctx:        plq.ctx.Clone(),
		order:      append([]policylabels.OrderOption{}, plq.order...),
		inters:     append([]Interceptor{}, plq.inters...),
		predicates: append([]predicate.PolicyLabels{}, plq.predicates...),
		withPolicy: plq.withPolicy.Clone(),
		// clone intermediate query.
		sql:  plq.sql.Clone(),
		path: plq.path,
	}
}

// WithPolicy tells the query-builder to eager-load the nodes that are connected to
// the "policy" edge. The optional arguments are used to configure the query builder of the edge.
func (plq *PolicyLabelsQuery) WithPolicy(opts ...func(*PoliciesQuery)) *PolicyLabelsQuery {
	query := (&PoliciesClient{config: plq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	plq.withPolicy = query
	return plq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PolicyID uuid.UUID `json:"policy_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PolicyLabels.Query().
//		GroupBy(policylabels.FieldPolicyID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (plq *PolicyLabelsQuery) GroupBy(field string, fields ...string) *PolicyLabelsGroupBy {
	plq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PolicyLabelsGroupBy{build: plq}
	grbuild.flds = &plq.ctx.Fields
	grbuild.label = policylabels.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PolicyID uuid.UUID `json:"policy_id,omitempty"`
//	}
//
//	client.PolicyLabels.Query().
//		Select(policylabels.FieldPolicyID).
//		Scan(ctx, &v)
func (plq *PolicyLabelsQuery) Select(fields ...string) *PolicyLabelsSelect {
	plq.ctx.Fields = append(plq.ctx.Fields, fields...)
	sbuild := &PolicyLabelsSelect{PolicyLabelsQuery: plq}
	sbuild.label = policylabels.Label
	sbuild.flds, sbuild.scan = &plq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PolicyLabelsSelect configured with the given aggregations.
func (plq *PolicyLabelsQuery) Aggregate(fns ...AggregateFunc) *PolicyLabelsSelect {
	return plq.Select().Aggregate(fns...)
}

func (plq *PolicyLabelsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range plq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, plq); err != nil {
				return err
			}
		}
	}
	for _, f := range plq.ctx.Fields {
		if !policylabels.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if plq.path != nil {
		prev, err := plq.path(ctx)
		if err != nil {
			return err
		}
		plq.sql = prev
	}
	return nil
}

func (plq *PolicyLabelsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PolicyLabels, error) {
	var (
		nodes       = []*PolicyLabels{}
		_spec       = plq.querySpec()
		loadedTypes = [1]bool{
			plq.withPolicy != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PolicyLabels).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PolicyLabels{config: plq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, plq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := plq.withPolicy; query != nil {
		if err := plq.loadPolicy(ctx, query, nodes, nil,
			func(n *PolicyLabels, e *Policies) { n.Edges.Policy = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (plq *PolicyLabelsQuery) loadPolicy(ctx context.Context, query *PoliciesQuery, nodes []*PolicyLabels, init func(*PolicyLabels), assign func(*PolicyLabels, *Policies)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PolicyLabels)
	for i := range nodes {
		fk := nodes[i].PolicyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(policies.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "policy_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (plq *PolicyLabelsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := plq.querySpec()
	_spec.Node.Columns = plq.ctx.Fields
	if len(plq.ctx.Fields) > 0 {
		_spec.Unique = plq.ctx.Unique != nil && *plq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, plq.driver, _spec)
}

func (plq *PolicyLabelsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(policylabels.Table, policylabels.Columns, sqlgraph.NewFieldSpec(policylabels.FieldID, field.TypeInt))
	_spec.From = plq.sql
	if unique := plq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if plq.path != nil {
		_spec.Unique = true
	}
	if fields := plq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, policylabels.FieldID)
		for i := range fields {
			if fields[i] != policylabels.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if plq.withPolicy != nil {
			_spec.Node.AddColumnOnce(policylabels.FieldPolicyID)
		}
	}
	if ps := plq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := plq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := plq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := plq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (plq *PolicyLabelsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(plq.driver.Dialect())
	t1 := builder.Table(policylabels.Table)
	columns := plq.ctx.Fields
	if len(columns) == 0 {
		columns = policylabels.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if plq.sql != nil {
		selector = plq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if plq.ctx.Unique != nil && *plq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range plq.predicates {
		p(selector)
	}
	for _, p := range plq.order {
		p(selector)
	}
	if offset := plq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := plq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PolicyLabelsGroupBy is the group-by builder for PolicyLabels entities.
type PolicyLabelsGroupBy struct {
	selector
	build *PolicyLabelsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (plgb *PolicyLabelsGroupBy) Aggregate(fns ...AggregateFunc) *PolicyLabelsGroupBy {
	plgb.fns = append(plgb.fns, fns...)
	return plgb
}

// Scan applies the selector query and scans the result into the given value.
func (plgb *PolicyLabelsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, plgb.build.ctx, ent.OpQueryGroupBy)
	if err := plgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PolicyLabelsQuery, *PolicyLabelsGroupBy](ctx, plgb.build, plgb, plgb.build.inters, v)
}

func (plgb *PolicyLabelsGroupBy) sqlScan(ctx context.Context, root *PolicyLabelsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(plgb.fns))
	for _, fn := range plgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*plgb.flds)+len(plgb.fns))
		for _, f := range *plgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*plgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := plgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PolicyLabelsSelect is the builder for selecting fields of PolicyLabels entities.
type PolicyLabelsSelect struct {
	*PolicyLabelsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pls *PolicyLabelsSelect) Aggregate(fns ...AggregateFunc) *PolicyLabelsSelect {
	pls.fns = append(pls.fns, fns...)
	return pls
}

// Scan applies the selector query and scans the result into the given value.
func (pls *PolicyLabelsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pls.ctx, ent.OpQuerySelect)
	if err := pls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PolicyLabelsQuery, *PolicyLabelsSelect](ctx, pls.PolicyLabelsQuery, pls, pls.inters, v)
}

func (pls *PolicyLabelsSelect) sqlScan(ctx context.Context, root *PolicyLabelsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pls.fns))
	for _, fn := range pls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
