// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shinobistack/gokakashi/ent/predicate"
	"github.com/shinobistack/gokakashi/ent/scanpolicy"
)

// ScanPolicyQuery is the builder for querying ScanPolicy entities.
type ScanPolicyQuery struct {
	config
	ctx        *QueryContext
	order      []scanpolicy.OrderOption
	inters     []Interceptor
	predicates []predicate.ScanPolicy
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScanPolicyQuery builder.
func (spq *ScanPolicyQuery) Where(ps ...predicate.ScanPolicy) *ScanPolicyQuery {
	spq.predicates = append(spq.predicates, ps...)
	return spq
}

// Limit the number of records to be returned by this query.
func (spq *ScanPolicyQuery) Limit(limit int) *ScanPolicyQuery {
	spq.ctx.Limit = &limit
	return spq
}

// Offset to start from.
func (spq *ScanPolicyQuery) Offset(offset int) *ScanPolicyQuery {
	spq.ctx.Offset = &offset
	return spq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (spq *ScanPolicyQuery) Unique(unique bool) *ScanPolicyQuery {
	spq.ctx.Unique = &unique
	return spq
}

// Order specifies how the records should be ordered.
func (spq *ScanPolicyQuery) Order(o ...scanpolicy.OrderOption) *ScanPolicyQuery {
	spq.order = append(spq.order, o...)
	return spq
}

// First returns the first ScanPolicy entity from the query.
// Returns a *NotFoundError when no ScanPolicy was found.
func (spq *ScanPolicyQuery) First(ctx context.Context) (*ScanPolicy, error) {
	nodes, err := spq.Limit(1).All(setContextOp(ctx, spq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{scanpolicy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (spq *ScanPolicyQuery) FirstX(ctx context.Context) *ScanPolicy {
	node, err := spq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ScanPolicy ID from the query.
// Returns a *NotFoundError when no ScanPolicy ID was found.
func (spq *ScanPolicyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = spq.Limit(1).IDs(setContextOp(ctx, spq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{scanpolicy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (spq *ScanPolicyQuery) FirstIDX(ctx context.Context) int {
	id, err := spq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ScanPolicy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ScanPolicy entity is found.
// Returns a *NotFoundError when no ScanPolicy entities are found.
func (spq *ScanPolicyQuery) Only(ctx context.Context) (*ScanPolicy, error) {
	nodes, err := spq.Limit(2).All(setContextOp(ctx, spq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{scanpolicy.Label}
	default:
		return nil, &NotSingularError{scanpolicy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (spq *ScanPolicyQuery) OnlyX(ctx context.Context) *ScanPolicy {
	node, err := spq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ScanPolicy ID in the query.
// Returns a *NotSingularError when more than one ScanPolicy ID is found.
// Returns a *NotFoundError when no entities are found.
func (spq *ScanPolicyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = spq.Limit(2).IDs(setContextOp(ctx, spq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{scanpolicy.Label}
	default:
		err = &NotSingularError{scanpolicy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (spq *ScanPolicyQuery) OnlyIDX(ctx context.Context) int {
	id, err := spq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ScanPolicies.
func (spq *ScanPolicyQuery) All(ctx context.Context) ([]*ScanPolicy, error) {
	ctx = setContextOp(ctx, spq.ctx, ent.OpQueryAll)
	if err := spq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ScanPolicy, *ScanPolicyQuery]()
	return withInterceptors[[]*ScanPolicy](ctx, spq, qr, spq.inters)
}

// AllX is like All, but panics if an error occurs.
func (spq *ScanPolicyQuery) AllX(ctx context.Context) []*ScanPolicy {
	nodes, err := spq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ScanPolicy IDs.
func (spq *ScanPolicyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if spq.ctx.Unique == nil && spq.path != nil {
		spq.Unique(true)
	}
	ctx = setContextOp(ctx, spq.ctx, ent.OpQueryIDs)
	if err = spq.Select(scanpolicy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (spq *ScanPolicyQuery) IDsX(ctx context.Context) []int {
	ids, err := spq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (spq *ScanPolicyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, spq.ctx, ent.OpQueryCount)
	if err := spq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, spq, querierCount[*ScanPolicyQuery](), spq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (spq *ScanPolicyQuery) CountX(ctx context.Context) int {
	count, err := spq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (spq *ScanPolicyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, spq.ctx, ent.OpQueryExist)
	switch _, err := spq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (spq *ScanPolicyQuery) ExistX(ctx context.Context) bool {
	exist, err := spq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScanPolicyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (spq *ScanPolicyQuery) Clone() *ScanPolicyQuery {
	if spq == nil {
		return nil
	}
	return &ScanPolicyQuery{
		config:     spq.config,
		ctx:        spq.ctx.Clone(),
		order:      append([]scanpolicy.OrderOption{}, spq.order...),
		inters:     append([]Interceptor{}, spq.inters...),
		predicates: append([]predicate.ScanPolicy{}, spq.predicates...),
		// clone intermediate query.
		sql:  spq.sql.Clone(),
		path: spq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ScanPolicy.Query().
//		GroupBy(scanpolicy.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (spq *ScanPolicyQuery) GroupBy(field string, fields ...string) *ScanPolicyGroupBy {
	spq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ScanPolicyGroupBy{build: spq}
	grbuild.flds = &spq.ctx.Fields
	grbuild.label = scanpolicy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ScanPolicy.Query().
//		Select(scanpolicy.FieldName).
//		Scan(ctx, &v)
func (spq *ScanPolicyQuery) Select(fields ...string) *ScanPolicySelect {
	spq.ctx.Fields = append(spq.ctx.Fields, fields...)
	sbuild := &ScanPolicySelect{ScanPolicyQuery: spq}
	sbuild.label = scanpolicy.Label
	sbuild.flds, sbuild.scan = &spq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ScanPolicySelect configured with the given aggregations.
func (spq *ScanPolicyQuery) Aggregate(fns ...AggregateFunc) *ScanPolicySelect {
	return spq.Select().Aggregate(fns...)
}

func (spq *ScanPolicyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range spq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, spq); err != nil {
				return err
			}
		}
	}
	for _, f := range spq.ctx.Fields {
		if !scanpolicy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if spq.path != nil {
		prev, err := spq.path(ctx)
		if err != nil {
			return err
		}
		spq.sql = prev
	}
	return nil
}

func (spq *ScanPolicyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ScanPolicy, error) {
	var (
		nodes = []*ScanPolicy{}
		_spec = spq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ScanPolicy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ScanPolicy{config: spq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, spq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (spq *ScanPolicyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := spq.querySpec()
	_spec.Node.Columns = spq.ctx.Fields
	if len(spq.ctx.Fields) > 0 {
		_spec.Unique = spq.ctx.Unique != nil && *spq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, spq.driver, _spec)
}

func (spq *ScanPolicyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(scanpolicy.Table, scanpolicy.Columns, sqlgraph.NewFieldSpec(scanpolicy.FieldID, field.TypeInt))
	_spec.From = spq.sql
	if unique := spq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if spq.path != nil {
		_spec.Unique = true
	}
	if fields := spq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scanpolicy.FieldID)
		for i := range fields {
			if fields[i] != scanpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := spq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := spq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := spq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := spq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (spq *ScanPolicyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(spq.driver.Dialect())
	t1 := builder.Table(scanpolicy.Table)
	columns := spq.ctx.Fields
	if len(columns) == 0 {
		columns = scanpolicy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if spq.sql != nil {
		selector = spq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if spq.ctx.Unique != nil && *spq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range spq.predicates {
		p(selector)
	}
	for _, p := range spq.order {
		p(selector)
	}
	if offset := spq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := spq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ScanPolicyGroupBy is the group-by builder for ScanPolicy entities.
type ScanPolicyGroupBy struct {
	selector
	build *ScanPolicyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (spgb *ScanPolicyGroupBy) Aggregate(fns ...AggregateFunc) *ScanPolicyGroupBy {
	spgb.fns = append(spgb.fns, fns...)
	return spgb
}

// Scan applies the selector query and scans the result into the given value.
func (spgb *ScanPolicyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, spgb.build.ctx, ent.OpQueryGroupBy)
	if err := spgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScanPolicyQuery, *ScanPolicyGroupBy](ctx, spgb.build, spgb, spgb.build.inters, v)
}

func (spgb *ScanPolicyGroupBy) sqlScan(ctx context.Context, root *ScanPolicyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(spgb.fns))
	for _, fn := range spgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*spgb.flds)+len(spgb.fns))
		for _, f := range *spgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*spgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := spgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ScanPolicySelect is the builder for selecting fields of ScanPolicy entities.
type ScanPolicySelect struct {
	*ScanPolicyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sps *ScanPolicySelect) Aggregate(fns ...AggregateFunc) *ScanPolicySelect {
	sps.fns = append(sps.fns, fns...)
	return sps
}

// Scan applies the selector query and scans the result into the given value.
func (sps *ScanPolicySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sps.ctx, ent.OpQuerySelect)
	if err := sps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScanPolicyQuery, *ScanPolicySelect](ctx, sps.ScanPolicyQuery, sps, sps.inters, v)
}

func (sps *ScanPolicySelect) sqlScan(ctx context.Context, root *ScanPolicyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sps.fns))
	for _, fn := range sps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
