// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shinobistack/gokakashi/ent/predicate"
	"github.com/shinobistack/gokakashi/ent/scanpolicy"
)

// ScanPolicyDelete is the builder for deleting a ScanPolicy entity.
type ScanPolicyDelete struct {
	config
	hooks    []Hook
	mutation *ScanPolicyMutation
}

// Where appends a list predicates to the ScanPolicyDelete builder.
func (spd *ScanPolicyDelete) Where(ps ...predicate.ScanPolicy) *ScanPolicyDelete {
	spd.mutation.Where(ps...)
	return spd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (spd *ScanPolicyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, spd.sqlExec, spd.mutation, spd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (spd *ScanPolicyDelete) ExecX(ctx context.Context) int {
	n, err := spd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (spd *ScanPolicyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(scanpolicy.Table, sqlgraph.NewFieldSpec(scanpolicy.FieldID, field.TypeInt))
	if ps := spd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, spd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	spd.mutation.done = true
	return affected, err
}

// ScanPolicyDeleteOne is the builder for deleting a single ScanPolicy entity.
type ScanPolicyDeleteOne struct {
	spd *ScanPolicyDelete
}

// Where appends a list predicates to the ScanPolicyDelete builder.
func (spdo *ScanPolicyDeleteOne) Where(ps ...predicate.ScanPolicy) *ScanPolicyDeleteOne {
	spdo.spd.mutation.Where(ps...)
	return spdo
}

// Exec executes the deletion query.
func (spdo *ScanPolicyDeleteOne) Exec(ctx context.Context) error {
	n, err := spdo.spd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{scanpolicy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (spdo *ScanPolicyDeleteOne) ExecX(ctx context.Context) {
	if err := spdo.Exec(ctx); err != nil {
		panic(err)
	}
}
