// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shinobistack/gokakashi/ent/predicate"
	"github.com/shinobistack/gokakashi/ent/scanlabels"
	"github.com/shinobistack/gokakashi/ent/scans"
)

// ScanLabelsQuery is the builder for querying ScanLabels entities.
type ScanLabelsQuery struct {
	config
	ctx        *QueryContext
	order      []scanlabels.OrderOption
	inters     []Interceptor
	predicates []predicate.ScanLabels
	withScan   *ScansQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScanLabelsQuery builder.
func (slq *ScanLabelsQuery) Where(ps ...predicate.ScanLabels) *ScanLabelsQuery {
	slq.predicates = append(slq.predicates, ps...)
	return slq
}

// Limit the number of records to be returned by this query.
func (slq *ScanLabelsQuery) Limit(limit int) *ScanLabelsQuery {
	slq.ctx.Limit = &limit
	return slq
}

// Offset to start from.
func (slq *ScanLabelsQuery) Offset(offset int) *ScanLabelsQuery {
	slq.ctx.Offset = &offset
	return slq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (slq *ScanLabelsQuery) Unique(unique bool) *ScanLabelsQuery {
	slq.ctx.Unique = &unique
	return slq
}

// Order specifies how the records should be ordered.
func (slq *ScanLabelsQuery) Order(o ...scanlabels.OrderOption) *ScanLabelsQuery {
	slq.order = append(slq.order, o...)
	return slq
}

// QueryScan chains the current query on the "scan" edge.
func (slq *ScanLabelsQuery) QueryScan() *ScansQuery {
	query := (&ScansClient{config: slq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := slq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := slq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scanlabels.Table, scanlabels.FieldID, selector),
			sqlgraph.To(scans.Table, scans.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scanlabels.ScanTable, scanlabels.ScanColumn),
		)
		fromU = sqlgraph.SetNeighbors(slq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ScanLabels entity from the query.
// Returns a *NotFoundError when no ScanLabels was found.
func (slq *ScanLabelsQuery) First(ctx context.Context) (*ScanLabels, error) {
	nodes, err := slq.Limit(1).All(setContextOp(ctx, slq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{scanlabels.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (slq *ScanLabelsQuery) FirstX(ctx context.Context) *ScanLabels {
	node, err := slq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ScanLabels ID from the query.
// Returns a *NotFoundError when no ScanLabels ID was found.
func (slq *ScanLabelsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = slq.Limit(1).IDs(setContextOp(ctx, slq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{scanlabels.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (slq *ScanLabelsQuery) FirstIDX(ctx context.Context) int {
	id, err := slq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ScanLabels entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ScanLabels entity is found.
// Returns a *NotFoundError when no ScanLabels entities are found.
func (slq *ScanLabelsQuery) Only(ctx context.Context) (*ScanLabels, error) {
	nodes, err := slq.Limit(2).All(setContextOp(ctx, slq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{scanlabels.Label}
	default:
		return nil, &NotSingularError{scanlabels.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (slq *ScanLabelsQuery) OnlyX(ctx context.Context) *ScanLabels {
	node, err := slq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ScanLabels ID in the query.
// Returns a *NotSingularError when more than one ScanLabels ID is found.
// Returns a *NotFoundError when no entities are found.
func (slq *ScanLabelsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = slq.Limit(2).IDs(setContextOp(ctx, slq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{scanlabels.Label}
	default:
		err = &NotSingularError{scanlabels.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (slq *ScanLabelsQuery) OnlyIDX(ctx context.Context) int {
	id, err := slq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ScanLabelsSlice.
func (slq *ScanLabelsQuery) All(ctx context.Context) ([]*ScanLabels, error) {
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryAll)
	if err := slq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ScanLabels, *ScanLabelsQuery]()
	return withInterceptors[[]*ScanLabels](ctx, slq, qr, slq.inters)
}

// AllX is like All, but panics if an error occurs.
func (slq *ScanLabelsQuery) AllX(ctx context.Context) []*ScanLabels {
	nodes, err := slq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ScanLabels IDs.
func (slq *ScanLabelsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if slq.ctx.Unique == nil && slq.path != nil {
		slq.Unique(true)
	}
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryIDs)
	if err = slq.Select(scanlabels.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (slq *ScanLabelsQuery) IDsX(ctx context.Context) []int {
	ids, err := slq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (slq *ScanLabelsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryCount)
	if err := slq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, slq, querierCount[*ScanLabelsQuery](), slq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (slq *ScanLabelsQuery) CountX(ctx context.Context) int {
	count, err := slq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (slq *ScanLabelsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, slq.ctx, ent.OpQueryExist)
	switch _, err := slq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (slq *ScanLabelsQuery) ExistX(ctx context.Context) bool {
	exist, err := slq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScanLabelsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (slq *ScanLabelsQuery) Clone() *ScanLabelsQuery {
	if slq == nil {
		return nil
	}
	return &ScanLabelsQuery{
		config:     slq.config,
		ctx:        slq.ctx.Clone(),
		order:      append([]scanlabels.OrderOption{}, slq.order...),
		inters:     append([]Interceptor{}, slq.inters...),
		predicates: append([]predicate.ScanLabels{}, slq.predicates...),
		withScan:   slq.withScan.Clone(),
		// clone intermediate query.
		sql:  slq.sql.Clone(),
		path: slq.path,
	}
}

// WithScan tells the query-builder to eager-load the nodes that are connected to
// the "scan" edge. The optional arguments are used to configure the query builder of the edge.
func (slq *ScanLabelsQuery) WithScan(opts ...func(*ScansQuery)) *ScanLabelsQuery {
	query := (&ScansClient{config: slq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	slq.withScan = query
	return slq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ScanID uuid.UUID `json:"scan_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ScanLabels.Query().
//		GroupBy(scanlabels.FieldScanID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (slq *ScanLabelsQuery) GroupBy(field string, fields ...string) *ScanLabelsGroupBy {
	slq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ScanLabelsGroupBy{build: slq}
	grbuild.flds = &slq.ctx.Fields
	grbuild.label = scanlabels.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ScanID uuid.UUID `json:"scan_id,omitempty"`
//	}
//
//	client.ScanLabels.Query().
//		Select(scanlabels.FieldScanID).
//		Scan(ctx, &v)
func (slq *ScanLabelsQuery) Select(fields ...string) *ScanLabelsSelect {
	slq.ctx.Fields = append(slq.ctx.Fields, fields...)
	sbuild := &ScanLabelsSelect{ScanLabelsQuery: slq}
	sbuild.label = scanlabels.Label
	sbuild.flds, sbuild.scan = &slq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ScanLabelsSelect configured with the given aggregations.
func (slq *ScanLabelsQuery) Aggregate(fns ...AggregateFunc) *ScanLabelsSelect {
	return slq.Select().Aggregate(fns...)
}

func (slq *ScanLabelsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range slq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, slq); err != nil {
				return err
			}
		}
	}
	for _, f := range slq.ctx.Fields {
		if !scanlabels.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if slq.path != nil {
		prev, err := slq.path(ctx)
		if err != nil {
			return err
		}
		slq.sql = prev
	}
	return nil
}

func (slq *ScanLabelsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ScanLabels, error) {
	var (
		nodes       = []*ScanLabels{}
		_spec       = slq.querySpec()
		loadedTypes = [1]bool{
			slq.withScan != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ScanLabels).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ScanLabels{config: slq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, slq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := slq.withScan; query != nil {
		if err := slq.loadScan(ctx, query, nodes, nil,
			func(n *ScanLabels, e *Scans) { n.Edges.Scan = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (slq *ScanLabelsQuery) loadScan(ctx context.Context, query *ScansQuery, nodes []*ScanLabels, init func(*ScanLabels), assign func(*ScanLabels, *Scans)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ScanLabels)
	for i := range nodes {
		fk := nodes[i].ScanID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(scans.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "scan_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (slq *ScanLabelsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := slq.querySpec()
	_spec.Node.Columns = slq.ctx.Fields
	if len(slq.ctx.Fields) > 0 {
		_spec.Unique = slq.ctx.Unique != nil && *slq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, slq.driver, _spec)
}

func (slq *ScanLabelsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(scanlabels.Table, scanlabels.Columns, sqlgraph.NewFieldSpec(scanlabels.FieldID, field.TypeInt))
	_spec.From = slq.sql
	if unique := slq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if slq.path != nil {
		_spec.Unique = true
	}
	if fields := slq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scanlabels.FieldID)
		for i := range fields {
			if fields[i] != scanlabels.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if slq.withScan != nil {
			_spec.Node.AddColumnOnce(scanlabels.FieldScanID)
		}
	}
	if ps := slq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := slq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := slq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := slq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (slq *ScanLabelsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(slq.driver.Dialect())
	t1 := builder.Table(scanlabels.Table)
	columns := slq.ctx.Fields
	if len(columns) == 0 {
		columns = scanlabels.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if slq.sql != nil {
		selector = slq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if slq.ctx.Unique != nil && *slq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range slq.predicates {
		p(selector)
	}
	for _, p := range slq.order {
		p(selector)
	}
	if offset := slq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := slq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ScanLabelsGroupBy is the group-by builder for ScanLabels entities.
type ScanLabelsGroupBy struct {
	selector
	build *ScanLabelsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (slgb *ScanLabelsGroupBy) Aggregate(fns ...AggregateFunc) *ScanLabelsGroupBy {
	slgb.fns = append(slgb.fns, fns...)
	return slgb
}

// Scan applies the selector query and scans the result into the given value.
func (slgb *ScanLabelsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, slgb.build.ctx, ent.OpQueryGroupBy)
	if err := slgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScanLabelsQuery, *ScanLabelsGroupBy](ctx, slgb.build, slgb, slgb.build.inters, v)
}

func (slgb *ScanLabelsGroupBy) sqlScan(ctx context.Context, root *ScanLabelsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(slgb.fns))
	for _, fn := range slgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*slgb.flds)+len(slgb.fns))
		for _, f := range *slgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*slgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := slgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ScanLabelsSelect is the builder for selecting fields of ScanLabels entities.
type ScanLabelsSelect struct {
	*ScanLabelsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sls *ScanLabelsSelect) Aggregate(fns ...AggregateFunc) *ScanLabelsSelect {
	sls.fns = append(sls.fns, fns...)
	return sls
}

// Scan applies the selector query and scans the result into the given value.
func (sls *ScanLabelsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sls.ctx, ent.OpQuerySelect)
	if err := sls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScanLabelsQuery, *ScanLabelsSelect](ctx, sls.ScanLabelsQuery, sls, sls.inters, v)
}

func (sls *ScanLabelsSelect) sqlScan(ctx context.Context, root *ScanLabelsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sls.fns))
	for _, fn := range sls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
