// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/shinobistack/gokakashi/ent/v2agenttasks"
)

// V2AgentTasks is the model entity for the V2AgentTasks schema.
type V2AgentTasks struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key, unique identifier.
	ID uuid.UUID `json:"id,omitempty"`
	// Foreign key to V2Agents.ID.
	AgentID uuid.UUID `json:"agent_id,omitempty"`
	// Foreign key to V2Scans.ID.
	ScanID uuid.UUID `json:"scan_id,omitempty"`
	// Enum: pending, in_progress, complete
	Status string `json:"status,omitempty"`
	// Timestamp for task creation.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Timestamp for task update.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*V2AgentTasks) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case v2agenttasks.FieldStatus:
			values[i] = new(sql.NullString)
		case v2agenttasks.FieldCreatedAt, v2agenttasks.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case v2agenttasks.FieldID, v2agenttasks.FieldAgentID, v2agenttasks.FieldScanID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the V2AgentTasks fields.
func (vt *V2AgentTasks) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case v2agenttasks.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				vt.ID = *value
			}
		case v2agenttasks.FieldAgentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value != nil {
				vt.AgentID = *value
			}
		case v2agenttasks.FieldScanID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field scan_id", values[i])
			} else if value != nil {
				vt.ScanID = *value
			}
		case v2agenttasks.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				vt.Status = value.String
			}
		case v2agenttasks.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				vt.CreatedAt = value.Time
			}
		case v2agenttasks.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				vt.UpdatedAt = value.Time
			}
		default:
			vt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the V2AgentTasks.
// This includes values selected through modifiers, order, etc.
func (vt *V2AgentTasks) Value(name string) (ent.Value, error) {
	return vt.selectValues.Get(name)
}

// Update returns a builder for updating this V2AgentTasks.
// Note that you need to call V2AgentTasks.Unwrap() before calling this method if this V2AgentTasks
// was returned from a transaction, and the transaction was committed or rolled back.
func (vt *V2AgentTasks) Update() *V2AgentTasksUpdateOne {
	return NewV2AgentTasksClient(vt.config).UpdateOne(vt)
}

// Unwrap unwraps the V2AgentTasks entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (vt *V2AgentTasks) Unwrap() *V2AgentTasks {
	_tx, ok := vt.config.driver.(*txDriver)
	if !ok {
		panic("ent: V2AgentTasks is not a transactional entity")
	}
	vt.config.driver = _tx.drv
	return vt
}

// String implements the fmt.Stringer.
func (vt *V2AgentTasks) String() string {
	var builder strings.Builder
	builder.WriteString("V2AgentTasks(")
	builder.WriteString(fmt.Sprintf("id=%v, ", vt.ID))
	builder.WriteString("agent_id=")
	builder.WriteString(fmt.Sprintf("%v", vt.AgentID))
	builder.WriteString(", ")
	builder.WriteString("scan_id=")
	builder.WriteString(fmt.Sprintf("%v", vt.ScanID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(vt.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(vt.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(vt.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// V2AgentTasksSlice is a parsable slice of V2AgentTasks.
type V2AgentTasksSlice []*V2AgentTasks
