// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/shinobistack/gokakashi/ent/predicate"
	"github.com/shinobistack/gokakashi/ent/v2scans"
)

// V2ScansQuery is the builder for querying V2Scans entities.
type V2ScansQuery struct {
	config
	ctx        *QueryContext
	order      []v2scans.OrderOption
	inters     []Interceptor
	predicates []predicate.V2Scans
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the V2ScansQuery builder.
func (vq *V2ScansQuery) Where(ps ...predicate.V2Scans) *V2ScansQuery {
	vq.predicates = append(vq.predicates, ps...)
	return vq
}

// Limit the number of records to be returned by this query.
func (vq *V2ScansQuery) Limit(limit int) *V2ScansQuery {
	vq.ctx.Limit = &limit
	return vq
}

// Offset to start from.
func (vq *V2ScansQuery) Offset(offset int) *V2ScansQuery {
	vq.ctx.Offset = &offset
	return vq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vq *V2ScansQuery) Unique(unique bool) *V2ScansQuery {
	vq.ctx.Unique = &unique
	return vq
}

// Order specifies how the records should be ordered.
func (vq *V2ScansQuery) Order(o ...v2scans.OrderOption) *V2ScansQuery {
	vq.order = append(vq.order, o...)
	return vq
}

// First returns the first V2Scans entity from the query.
// Returns a *NotFoundError when no V2Scans was found.
func (vq *V2ScansQuery) First(ctx context.Context) (*V2Scans, error) {
	nodes, err := vq.Limit(1).All(setContextOp(ctx, vq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{v2scans.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vq *V2ScansQuery) FirstX(ctx context.Context) *V2Scans {
	node, err := vq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first V2Scans ID from the query.
// Returns a *NotFoundError when no V2Scans ID was found.
func (vq *V2ScansQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = vq.Limit(1).IDs(setContextOp(ctx, vq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{v2scans.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vq *V2ScansQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := vq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single V2Scans entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one V2Scans entity is found.
// Returns a *NotFoundError when no V2Scans entities are found.
func (vq *V2ScansQuery) Only(ctx context.Context) (*V2Scans, error) {
	nodes, err := vq.Limit(2).All(setContextOp(ctx, vq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{v2scans.Label}
	default:
		return nil, &NotSingularError{v2scans.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vq *V2ScansQuery) OnlyX(ctx context.Context) *V2Scans {
	node, err := vq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only V2Scans ID in the query.
// Returns a *NotSingularError when more than one V2Scans ID is found.
// Returns a *NotFoundError when no entities are found.
func (vq *V2ScansQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = vq.Limit(2).IDs(setContextOp(ctx, vq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{v2scans.Label}
	default:
		err = &NotSingularError{v2scans.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vq *V2ScansQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := vq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of V2ScansSlice.
func (vq *V2ScansQuery) All(ctx context.Context) ([]*V2Scans, error) {
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryAll)
	if err := vq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*V2Scans, *V2ScansQuery]()
	return withInterceptors[[]*V2Scans](ctx, vq, qr, vq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vq *V2ScansQuery) AllX(ctx context.Context) []*V2Scans {
	nodes, err := vq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of V2Scans IDs.
func (vq *V2ScansQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if vq.ctx.Unique == nil && vq.path != nil {
		vq.Unique(true)
	}
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryIDs)
	if err = vq.Select(v2scans.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vq *V2ScansQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := vq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vq *V2ScansQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryCount)
	if err := vq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vq, querierCount[*V2ScansQuery](), vq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vq *V2ScansQuery) CountX(ctx context.Context) int {
	count, err := vq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vq *V2ScansQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vq.ctx, ent.OpQueryExist)
	switch _, err := vq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vq *V2ScansQuery) ExistX(ctx context.Context) bool {
	exist, err := vq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the V2ScansQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vq *V2ScansQuery) Clone() *V2ScansQuery {
	if vq == nil {
		return nil
	}
	return &V2ScansQuery{
		config:     vq.config,
		ctx:        vq.ctx.Clone(),
		order:      append([]v2scans.OrderOption{}, vq.order...),
		inters:     append([]Interceptor{}, vq.inters...),
		predicates: append([]predicate.V2Scans{}, vq.predicates...),
		// clone intermediate query.
		sql:  vq.sql.Clone(),
		path: vq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.V2Scans.Query().
//		GroupBy(v2scans.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vq *V2ScansQuery) GroupBy(field string, fields ...string) *V2ScansGroupBy {
	vq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &V2ScansGroupBy{build: vq}
	grbuild.flds = &vq.ctx.Fields
	grbuild.label = v2scans.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//	}
//
//	client.V2Scans.Query().
//		Select(v2scans.FieldStatus).
//		Scan(ctx, &v)
func (vq *V2ScansQuery) Select(fields ...string) *V2ScansSelect {
	vq.ctx.Fields = append(vq.ctx.Fields, fields...)
	sbuild := &V2ScansSelect{V2ScansQuery: vq}
	sbuild.label = v2scans.Label
	sbuild.flds, sbuild.scan = &vq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a V2ScansSelect configured with the given aggregations.
func (vq *V2ScansQuery) Aggregate(fns ...AggregateFunc) *V2ScansSelect {
	return vq.Select().Aggregate(fns...)
}

func (vq *V2ScansQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vq); err != nil {
				return err
			}
		}
	}
	for _, f := range vq.ctx.Fields {
		if !v2scans.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vq.path != nil {
		prev, err := vq.path(ctx)
		if err != nil {
			return err
		}
		vq.sql = prev
	}
	return nil
}

func (vq *V2ScansQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*V2Scans, error) {
	var (
		nodes = []*V2Scans{}
		_spec = vq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*V2Scans).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &V2Scans{config: vq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (vq *V2ScansQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vq.querySpec()
	_spec.Node.Columns = vq.ctx.Fields
	if len(vq.ctx.Fields) > 0 {
		_spec.Unique = vq.ctx.Unique != nil && *vq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vq.driver, _spec)
}

func (vq *V2ScansQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(v2scans.Table, v2scans.Columns, sqlgraph.NewFieldSpec(v2scans.FieldID, field.TypeUUID))
	_spec.From = vq.sql
	if unique := vq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vq.path != nil {
		_spec.Unique = true
	}
	if fields := vq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, v2scans.FieldID)
		for i := range fields {
			if fields[i] != v2scans.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vq *V2ScansQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vq.driver.Dialect())
	t1 := builder.Table(v2scans.Table)
	columns := vq.ctx.Fields
	if len(columns) == 0 {
		columns = v2scans.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vq.sql != nil {
		selector = vq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vq.ctx.Unique != nil && *vq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vq.predicates {
		p(selector)
	}
	for _, p := range vq.order {
		p(selector)
	}
	if offset := vq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// V2ScansGroupBy is the group-by builder for V2Scans entities.
type V2ScansGroupBy struct {
	selector
	build *V2ScansQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vgb *V2ScansGroupBy) Aggregate(fns ...AggregateFunc) *V2ScansGroupBy {
	vgb.fns = append(vgb.fns, fns...)
	return vgb
}

// Scan applies the selector query and scans the result into the given value.
func (vgb *V2ScansGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vgb.build.ctx, ent.OpQueryGroupBy)
	if err := vgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*V2ScansQuery, *V2ScansGroupBy](ctx, vgb.build, vgb, vgb.build.inters, v)
}

func (vgb *V2ScansGroupBy) sqlScan(ctx context.Context, root *V2ScansQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vgb.fns))
	for _, fn := range vgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vgb.flds)+len(vgb.fns))
		for _, f := range *vgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// V2ScansSelect is the builder for selecting fields of V2Scans entities.
type V2ScansSelect struct {
	*V2ScansQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vs *V2ScansSelect) Aggregate(fns ...AggregateFunc) *V2ScansSelect {
	vs.fns = append(vs.fns, fns...)
	return vs
}

// Scan applies the selector query and scans the result into the given value.
func (vs *V2ScansSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vs.ctx, ent.OpQuerySelect)
	if err := vs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*V2ScansQuery, *V2ScansSelect](ctx, vs.V2ScansQuery, vs, vs.inters, v)
}

func (vs *V2ScansSelect) sqlScan(ctx context.Context, root *V2ScansQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vs.fns))
	for _, fn := range vs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
