// Code generated by ent, DO NOT EDIT.

package scannotify

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/shinobistack/gokakashi/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldLTE(FieldID, id))
}

// ScanID applies equality check predicate on the "scan_id" field. It's identical to ScanIDEQ.
func ScanID(v uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEQ(FieldScanID, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEQ(FieldHash, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEQ(FieldStatus, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEQ(FieldUpdatedAt, v))
}

// ScanIDEQ applies the EQ predicate on the "scan_id" field.
func ScanIDEQ(v uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEQ(FieldScanID, v))
}

// ScanIDNEQ applies the NEQ predicate on the "scan_id" field.
func ScanIDNEQ(v uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldNEQ(FieldScanID, v))
}

// ScanIDIn applies the In predicate on the "scan_id" field.
func ScanIDIn(vs ...uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldIn(FieldScanID, vs...))
}

// ScanIDNotIn applies the NotIn predicate on the "scan_id" field.
func ScanIDNotIn(vs ...uuid.UUID) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldNotIn(FieldScanID, vs...))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldContainsFold(FieldHash, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldContainsFold(FieldStatus, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ScanNotify {
	return predicate.ScanNotify(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasScan applies the HasEdge predicate on the "scan" edge.
func HasScan() predicate.ScanNotify {
	return predicate.ScanNotify(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScanTable, ScanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScanWith applies the HasEdge predicate on the "scan" edge with a given conditions (other predicates).
func HasScanWith(preds ...predicate.Scans) predicate.ScanNotify {
	return predicate.ScanNotify(func(s *sql.Selector) {
		step := newScanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScanNotify) predicate.ScanNotify {
	return predicate.ScanNotify(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScanNotify) predicate.ScanNotify {
	return predicate.ScanNotify(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScanNotify) predicate.ScanNotify {
	return predicate.ScanNotify(sql.NotPredicates(p))
}
