name: Test GoKakashi Scan

on:
  workflow_dispatch:  # Allows you to trigger the workflow manually
  push:
    branches:
      - build-github-actions

jobs:
  test-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run GoKakashi Scan
        uses: ./.github/actions/gokakashi-scan
        with:
          api_host: 'http://localhost:8000'
          api_token: 'ashwiniag123'
          image_name: 'hasura/graphql-engine:v2.35.0'
          severity: 'CRITICAL,HIGH'
          publish: 'report_private'
          fail_on_severity: 'HIGH,CRITICAL'

      - name: Log the Scan Report URL
        run: |
          echo "Scan report URL: ${{ steps.scan.outputs.report_url }}"