name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: actions/setup-node@v3
        with:
          node-version: "21.x"
      - name: Install dependencies
        working-directory: ./webapp
        run: npm ci
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
