name: Release GoKakashi Agent

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release (e.g., v0.1.0)"
        required: true
      name:
        description: "Name for the release (e.g., v0.1.0 Chidori)"
        required: false

jobs:
  build-and-release-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Tidy Up Go Modules
        run: go mod tidy

      - name: Install Dependencies (webapp)
          run: |
            npm install
            npm run build
          working-directory: ./webapp

      - name: Build Binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/gokakashi-agent-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/gokakashi-agent-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -o dist/gokakashi-agent-mac-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o dist/gokakashi-agent-mac-arm64 .
          GOOS=windows GOARCH=amd64 go build -o dist/gokakashi-agent-windows-amd64.exe .

      - name: Upload Release Binaries
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: dist/*
          name: ${{ github.event.inputs.name }}
          body: "🚀"