name: Release GoKakashi Agent

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-release-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build Binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/gokakashi-agent-linux-amd64 ./cmd/agent.go
          GOOS=linux GOARCH=arm64 go build -o dist/gokakashi-agent-linux-arm64 ./cmd/agent.go
          GOOS=darwin GOARCH=amd64 go build -o dist/gokakashi-agent-mac-amd64 ./cmd/agent.go
          GOOS=darwin GOARCH=arm64 go build -o dist/gokakashi-agent-mac-arm64 ./cmd/agent.go
          GOOS=windows GOARCH=amd64 go build -o dist/gokakashi-agent-windows-amd64.exe ./cmd/agent.go

      - name: Upload Release Binaries
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body: "🚀 GoKakashi Agent Release - See Changelog for Details!"