name: Test GoKakashi Scan

on:
  workflow_dispatch:
  push:
    branches:
      - build-github-actions-2

jobs:
  test-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run GoKakashi Scan
        id: gokakashi_scan
        uses: ./.github/actions/gokakashi-scan
        with:
          api_host: 'https://private-scan-reports.hasura-app.io:9090'
          api_token: 'ashwiniag123'
          image_name: 'hasura/graphql-engine:v2.35.0'
          severity: 'CRITICAL,HIGH'
          publish: 'report_private'
          # fail_on_severity: 'HIGH,CRITICAL'

      - name: Log the Scan Report URL
        run: |
          echo "Scan report URL: ${{ steps.gokakashi_scan.outputs.report_url }}"