// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// IntegrationType is the predicate function for integrationtype builders.
type IntegrationType func(*sql.Selector)

// Integrations is the predicate function for integrations builders.
type Integrations func(*sql.Selector)

// Policies is the predicate function for policies builders.
type Policies func(*sql.Selector)

// PolicyLabels is the predicate function for policylabels builders.
type PolicyLabels func(*sql.Selector)
