// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AgentTasks is the predicate function for agenttasks builders.
type AgentTasks func(*sql.Selector)

// Agents is the predicate function for agents builders.
type Agents func(*sql.Selector)

// IntegrationType is the predicate function for integrationtype builders.
type IntegrationType func(*sql.Selector)

// Integrations is the predicate function for integrations builders.
type Integrations func(*sql.Selector)

// Policies is the predicate function for policies builders.
type Policies func(*sql.Selector)

// PolicyLabels is the predicate function for policylabels builders.
type PolicyLabels func(*sql.Selector)

// ScanLabels is the predicate function for scanlabels builders.
type ScanLabels func(*sql.Selector)

// Scans is the predicate function for scans builders.
type Scans func(*sql.Selector)
